title: DeviceCredentialDeployment Execution
id: b8b1b304-a60f-4999-9a6e-c547bde03ffd
status: test
description: Detects the execution of DeviceCredentialDeployment to hide a process
  from view
references:
- https://github.com/LOLBAS-Project/LOLBAS/pull/147
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-08-19
tags:
- attack.defense-evasion
- attack.t1218
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: '\DeviceCredentialDeployment.exe'
  condition: selection
falsepositives:
- Unlikely
level: medium
notes: |
  ### Technical Context
  This Sigma rule is designed to detect the execution of the `DeviceCredentialDeployment.exe` process, which may be leveraged by malicious actors to conceal other processes from visibility. While `DeviceCredentialDeployment.exe` has legitimate uses, its execution in unconventional contexts can indicate attempts to evade detection mechanisms. The rule monitors process creation logs specifically, identifying instances where this executable is launched. An anomaly can arise when such executions occur without corresponding valid user behavior or within rare execution patterns, warranting further investigation.
  The underlying data sources for this detection include Windows process creation logs, which provide valuable insights into the command lines, user accounts, and other attributes associated with executed processes. An effective investigation will focus on identifying the context and motivations behind such executions.
  ### Investigation Steps
  - Review the related process creation logs in your EDR or SIEM to ascertain the execution context of `DeviceCredentialDeployment.exe`, including the user and time of execution.
  - Check for any unusual command-line arguments associated with the process to determine if any are indicative of nefarious intent or misuse.
  - Correlate the observed execution with other logs, such as authentication logs, to identify any suspicious user behaviors or activities leading up to the event.
  - Utilize your antivirus solution to scan the affected system for any known threats or indications of compromise associated with this process execution.
