title: Potential Signing Bypass Via Windows Developer Features
id: a383dec4-deec-4e6e-913b-ed9249670848
related:
- id: b110ebaf-697f-4da1-afd5-b536fa27a2c1
  type: similar
status: test
description: Detects when a user enable developer features such as "Developer Mode"
  or "Application Sideloading". Which allows the user to install untrusted packages.
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-01-11
tags:
- attack.defense-evasion
logsource:
  category: process_creation
  product: windows
detection:
  selection_img:
  - Image|endswith: '\SystemSettingsAdminFlows.exe'
  - OriginalFileName: 'SystemSettingsAdminFlows.EXE'
  selection_flag:
    CommandLine|contains: 'TurnOnDeveloperFeatures'
  selection_options:
    CommandLine|contains:
    - 'DeveloperUnlock'
    - 'EnableSideloading'
  condition: all of selection_*
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  This detection rule aims to identify instances where users enable Windows developer features that can introduce security risks, such as "Developer Mode" or "Application Sideloading." These features allow for the installation of unsigned applications, which can facilitate malware deployment and bypass traditional security measures. The rule specifically looks for process creation logs related to the `SystemSettingsAdminFlows.exe` executable, which is involved in modifying system settings for development purposes. The detection mechanism also examines command-line parameters to identify specific flags like `TurnOnDeveloperFeatures`, `DeveloperUnlock`, and `EnableSideloading`. By monitoring these parameters, security analysts can detect potentially risky behavior indicative of an attempt to execute or deploy untrusted applications within the enterprise environment.
  ### Investigation Steps
  - Review process creation logs in the EDR tool to confirm instances of `SystemSettingsAdminFlows.exe` and the associated command-line arguments indicating the activation of developer features.
  - Check for any related alerts from the AV solution that may indicate the installation of untrusted or malicious software following the enabling of developer features.
  - Examine proxy logs to identify any unusual outbound connections or downloads that coincide with the time the developer features were activated.
  - Cross-reference cloud logs in AWS, GCP, or Azure to detect any abnormal activities associated with the user account that enabled these features, including access to potentially malicious scripts or packages.
