title: Potential Signing Bypass Via Windows Developer Features
id: a383dec4-deec-4e6e-913b-ed9249670848
related:
- id: b110ebaf-697f-4da1-afd5-b536fa27a2c1
  type: similar
status: test
description: Detects when a user enable developer features such as "Developer Mode"
  or "Application Sideloading". Which allows the user to install untrusted packages.
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-01-11
tags:
- attack.defense-evasion
logsource:
  category: process_creation
  product: windows
detection:
  selection_img:
  - Image|endswith: '\SystemSettingsAdminFlows.exe'
  - OriginalFileName: 'SystemSettingsAdminFlows.EXE'
  selection_flag:
    CommandLine|contains: 'TurnOnDeveloperFeatures'
  selection_options:
    CommandLine|contains:
    - 'DeveloperUnlock'
    - 'EnableSideloading'
  condition: all of selection_*
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  This Sigma rule identifies potential security risks associated with enabling Windows Developer features like "Developer Mode" and "Application Sideloading," which can allow users to install untrusted applications. The detection focuses on process creation logs generated by Windows, targeting specific indicators such as the execution of `SystemSettingsAdminFlows.exe`, which is the Windows component responsible for changing system settings, and command-line parameters related to developer features. The relevant MITRE ATT&CK tactics involved here include **Defense Evasion**, specifically the technique of bypassing protections that prevent the execution of untrusted software. By monitoring for the presence of keywords like "TurnOnDeveloperFeatures", "DeveloperUnlock", and "EnableSideloading" in the command line, the rule alerts when a user takes actions that could expose the system to unverified applications and potential malware.
  ### Investigation Steps
  - **Review EDR Alerts**: Check EDR logs for additional context around the process creation event, confirming whether the process was launched from an authorized user account and if any suspicious behavior followed.
  - **Analyze Command-Line Parameters**: Investigate the command-line history pertaining to the alert to determine if other known vulnerabilities or risks were activated concurrently with enabling developer features.
  - **Evaluate System Changes**: Use Windows Event Logs to review any changes to security settings or newly installed applications subsequent to the developer mode being enabled, which can indicate whether any untrusted software was deployed.
  - **Threat Intelligence Lookup**: Perform a lookup against threat intelligence databases to assess if similar alerts have been accompanied by recognized malicious activity tied to enabling developer features on other systems.
  ### Prioritization
  This alert is considered high severity due to the significant risk associated with enabling developer features, which can lead to the installation of untrusted and potentially harmful applications, compromising the security integrity of the enterprise environment.
  ### Blind Spots and Assumptions
  The rule may not fire in environments where developer features are already enabled by legitimate users, as this could create noise and result in false positives. Furthermore, if an adversary uses custom methods of script execution or tools that do not invoke `SystemSettingsAdminFlows.exe`, the detection may be bypassed entirely. It is also assumed that all command-line activity is logged; environments without complete monitoring may fail to capture these necessary indicators.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and clarity, we recommend validating the content and adapting it to suit your specific environment and operational needs. Please communicate any changes to the detection engineering team.
