title: Arbitrary File Download Via ConfigSecurityPolicy.EXE
id: 1f0f6176-6482-4027-b151-00071af39d7e
status: test
description: |
  Detects the execution of "ConfigSecurityPolicy.EXE", a binary part of Windows Defender used to manage settings in Windows Defender.
  Users can configure different pilot collections for each of the co-management workloads.
  It can be abused by attackers in order to upload or download files.
references:
- https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
author: frack113
date: 2021-11-26
modified: 2022-05-16
tags:
- attack.exfiltration
- attack.t1567
logsource:
  category: process_creation
  product: windows
detection:
  selection_img:
  - CommandLine|contains: ConfigSecurityPolicy.exe
  - Image|endswith: '\ConfigSecurityPolicy.exe'
  - OriginalFileName: 'ConfigSecurityPolicy.exe'
  selection_url:
    CommandLine|contains:
    - 'ftp://'
    - 'http://'
    - 'https://'
  condition: all of selection_*
falsepositives:
- Unknown
level: medium
notes: |
  ### Technical Context
  The detection rule "Arbitrary File Download Via ConfigSecurityPolicy.EXE" monitors the execution of the "ConfigSecurityPolicy.EXE" process, which is a legitimate binary associated with Windows Defender used for managing configuration settings. This rule primarily relies on process creation logs, analyzing command line parameters and image names to detect potential misuse. The rule specifically looks for instances where the command line includes calls to download files from external sources (i.e., URLs beginning with 'http', 'https', or 'ftp'). The intent behind this monitoring is to identify potential data exfiltration attempts or other malicious activities leveraging this Windows Defender utility. This aligns with the MITRE ATT&CK framework under the tactic of "Exfiltration" (T1567), which addresses the use of legitimate tools for unauthorized information removal.
  ### Investigation Steps
  - **Check Process Creation Logs:** Review the recent process creation events in your EDR tool to identify instances of `ConfigSecurityPolicy.EXE`. Ensure the command line used matches the criteria set in the detection rule.
  - **Review Connection Logs:** Use network logs to investigate any outbound connections made during the same timeframe as the detected process execution. Specifically, look for any connections to URLs with 'http', 'https', or 'ftp'.
  - **Analyze File Activities:** Inspect any file system events related to the execution of `ConfigSecurityPolicy.EXE` to determine if any unauthorized files were downloaded or uploaded.
  - **Investigate Associated User Activity:** Assess the user account that initiated the process for any anomalous behavior or deviation from standard operating procedures, particularly focusing on account privileges and recent access logs.
  ### Prioritization
  This alert is assigned a medium severity level due to the potential for data exfiltration through a seemingly benign process. While `ConfigSecurityPolicy.EXE` is a legitimate Windows utility, its misuse could indicate an attacker leveraging native tools for malicious purposes, warranting further investigation.
  ### Blind Spots and Assumptions
  This rule may not detect instances where an adversary manipulates the process name or disguises their command execution to evade detection. Additionally, if the binary is executed with limited network connectivity or if the attacker uses alternate means to exfiltrate data, the rule may fail to trigger. It is assumed that environments where `ConfigSecurityPolicy.EXE` is utilized legitimately on a regular basis may generate false positives that need to be examined further by the SOC team.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and accuracy, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
