title: Start of NT Virtual DOS Machine
id: 16905e21-66ee-42fe-b256-1318ada2d770
status: test
description: Ntvdm.exe allows the execution of 16-bit Windows applications on 32-bit
  Windows operating systems, as well as the execution of both 16-bit and 32-bit DOS
  applications
references:
- https://learn.microsoft.com/en-us/windows/compatibility/ntvdm-and-16-bit-app-support
- https://support.microsoft.com/fr-fr/topic/an-ms-dos-based-program-that-uses-the-ms-dos-protected-mode-interface-crashes-on-a-computer-that-is-running-windows-7-5dc739ea-987b-b458-15e4-d28d5cca63c7
- https://app.any.run/tasks/93fe92fa-8b2b-4d92-8c09-a841aed2e793/
- https://app.any.run/tasks/214094a7-0abc-4a7b-a564-1b757faed79d/
author: frack113
date: 2022-07-16
modified: 2022-07-16
tags:
- attack.defense-evasion
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith:
    - '\ntvdm.exe'
    - '\csrstub.exe'
  condition: selection
falsepositives:
- Legitimate use
level: medium
notes: |
  ### Technical Context
  The Sigma rule titled "Start of NT Virtual DOS Machine" focuses on the detection of suspicious behavior through the monitoring of process creation events related to the execution of `ntvdm.exe` (NT Virtual DOS Machine) and `csrstub.exe`. These executables are responsible for enabling compatibility with 16-bit Windows applications on modern 32-bit Windows operating systems. The rule monitors for instances where these processes are initiated, as their execution can signify potential exploitation or misuse by threat actors employing legacy software. By analyzing the `process_creation` logs from Windows environments, the detection leverages key attributes such as the process image name to identify unexpected or unauthorized executions that align with MITRE ATT&CK's Defense Evasion techniques, specifically related to the evasion of detection through the use of legacy technologies. 
  ### Investigation Steps
  - **Verify Process Origins:** Check the execution path of the detected processes in the EDR solution to determine if they originate from expected system directories or user space, as unexpected paths may indicate adversarial activity.
  - **Analyze Command-Line Parameters:** Review the associated command-line arguments in the process creation logs to understand the intention behind the execution and detect any potentially malicious parameters or scripts.
  - **Cross-reference with Security Logs:** Consult Windows Security Logs to identify any anomalous user activity or system events correlating with the process creation, which could provide context for the alert.
  - **Network Correlation:** Utilize Network Detection and Response (NDR) solutions to analyze any network connections that occurred after the execution of the processes, looking for communication with known malicious IPs or domains.
  ### Prioritization
  The alert is classified as medium severity in an enterprise environment due to the potential risk that the execution of NT Virtual DOS Machine processes may indicate underlying threats, especially in systems where legacy software is not commonly used or where its use is not justified.
  ### Blind Spots and Assumptions
  This rule assumes that the execution of `ntvdm.exe` and `csrstub.exe` is a rare event in the monitored environment. However, legitimate use cases may lead to false positives, as some users or applications may require these processes to run older software. Additionally, if an attacker disables process creation logging or if the process names are obscured through renaming or other evasion tactics, this rule may not trigger, thereby creating a potential blind spot for detection.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
