title: Using SettingSyncHost.exe as LOLBin
id: b2ddd389-f676-4ac4-845a-e00781a48e5f
status: test
description: Detects using SettingSyncHost.exe to run hijacked binary
references:
- https://www.hexacorn.com/blog/2020/02/02/settingsynchost-exe-as-a-lolbin
author: Anton Kutepov, oscd.community
date: 2020-02-05
modified: 2021-11-27
tags:
- attack.execution
- attack.defense-evasion
- attack.t1574.008
logsource:
  category: process_creation
  product: windows
detection:
  system_utility:
    Image|startswith:
    - 'C:\Windows\System32\'
    - 'C:\Windows\SysWOW64\'
  parent_is_settingsynchost:
    ParentCommandLine|contains|all:
    - 'cmd.exe /c'
    - 'RoamDiag.cmd'
    - '-outputpath'
  condition: not system_utility and parent_is_settingsynchost
fields:
- TargetFilename
- Image
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  The Sigma rule "Using SettingSyncHost.exe as LOLBin" is designed to detect instances where a legitimate system utility, `SettingSyncHost.exe`, is misused to execute a malicious or hijacked binary. This is identified by monitoring process creation events within Windows that show certain command line patterns associated with `cmd.exe` and `RoamDiag.cmd`, which are often indicative of an attempted abuse for malicious purposes. Specifically, the rule captures cases where `SettingSyncHost.exe` serves as a parent process to another executable that is not a standard system utility, thus revealing potential exploitation tactics as defined in the MITRE ATT&CK framework under T1574.008 (Hijack Execution Flow: Dynamic Link Library Injection). The primary telemetry sources utilized include process creation logs from Windows, enabling the detection of unusual parent-child process relationships that could indicate abuse of legitimate binaries.
  ### Investigation Steps
  - **Examine Process Creation Logs**: Utilize EDR tools to explore any recent instances of `SettingSyncHost.exe` as the parent process for other binaries, focusing on timestamps and command-line arguments.
    
  - **Review Command Line Arguments**: Check for the presence of `cmd.exe /c` and `RoamDiag.cmd` in the process execution commands to confirm the use of these hijacked execution methods and analyze any associated parameters.
  - **Correlate with Other Logs**: Investigate Windows Security or Sysmon logs to cross-reference any suspicious commands, particularly those involving `SettingSyncHost.exe`, looking out for backdoors or other indicators of compromise.
  - **Check for File Integrity**: Use file monitoring tools to assess the target filenames invoked by the rogue processes, ensuring they match against known hashes of benign binaries to identify potential malicious artifacts.
  ### Prioritization
  Given that this rule is classified as "high" severity, the firing of this alert indicates a considerable risk of an advanced adversary executing malicious code under the guise of a legitimate Windows utility, warranting immediate investigation to prevent potential data breaches or system compromises.
  ### Blind Spots and Assumptions
  This rule may not fire in environments where `SettingSyncHost.exe` is legitimately used for purposes that include command execution or where user environment policies allow for atypical command line usage. Additionally, if an attacker modifies the command line to exclude the expected parameters or uses native tools that do not trigger typical process creation events, the detection may fail. Analysts should be aware that while monitoring can capture known exploit patterns, new tactics or variations may bypass this detection.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and applicability to detection tuning, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
