title: DeviceCredentialDeployment Execution
id: b8b1b304-a60f-4999-9a6e-c547bde03ffd
status: test
description: Detects the execution of DeviceCredentialDeployment to hide a process
  from view
references:
- https://github.com/LOLBAS-Project/LOLBAS/pull/147
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-08-19
tags:
- attack.defense-evasion
- attack.t1218
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: '\DeviceCredentialDeployment.exe'
  condition: selection
falsepositives:
- Unlikely
level: medium
notes: |
  n
  ### Technical Context
  This detection rule identifies the execution of `DeviceCredentialDeployment.exe`, a legitimate Windows process associated with credential management for devices. The primary objective of this rule is to highlight instances where this process is invoked potentially for malicious purposes, such as hiding other processes or evading detection mechanisms, which aligns with the MITRE ATT&CK technique T1218 (Signed Binary Proxy Execution). The rule relies on data sourced from Windows process creation logs, specifically examining the process image name to determine if it ends with `DeviceCredentialDeployment.exe`. 
  ### Investigation Steps
  - **Review Process Execution**: Look for the execution of `DeviceCredentialDeployment.exe` in your EDR's process creation logs. Check the parent process and command-line arguments to identify the origin of the execution.
  - **Correlate with Other Activities**: Inspect nearby events that may indicate suspicious behavior, such as unusual network connections or process access involving sensitive or known malicious applications in your SIEM.
  - **Analyze User Context**: Verify who executed the process by reviewing Windows Security logs related to user authentication at the time of the process execution. Determine if this aligns with normal user activity.
  - **Probe Surrounding Network Behavior**: Utilize network detection tools to analyze if there are any exfiltration attempts or unusual DNS queries associated with the device during the time this process ran.
  ### Prioritization
  The alert is marked with a medium severity level due to the potential misuse of a legitimate process to conceal malicious activities, which could impact overall operational security.
  ### Blind Spots and Assumptions
  This rule may not trigger if an adversary uses alternative methods to execute similar functionalities without utilizing DeviceCredentialDeployment.exe, or if they directly manipulate it in a manner that circumvents traditional detection via obfuscation techniques. Additionally, the rule assumes that the standard telemetry for process creation is being correctly collected and monitored. In environments with restrictive logging, this detection may also fail to activate due to lack of visibility into process execution events.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
