title: Application Removed Via Wmic.EXE
id: b53317a0-8acf-4fd1-8de8-a5401e776b96
related:
- id: 847d5ff3-8a31-4737-a970-aeae8fe21765     # Uninstall Security Products
  type: derived
status: test
description: Detects the removal or uninstallation of an application via "Wmic.EXE".
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
author: frack113
date: 2022-01-28
modified: 2024-07-02
tags:
- attack.execution
- attack.t1047
logsource:
  category: process_creation
  product: windows
detection:
  selection_img:
  - Image|endswith: '\WMIC.exe'
  - OriginalFileName: 'wmic.exe'
  selection_cli:
    CommandLine|contains|all:
    - 'call'
    - 'uninstall'
  condition: all of selection_*
falsepositives:
- Unknown
level: medium
notes: |
  ### Technical Context
  This detection rule identifies unauthorized uninstallation of applications using the Windows Management Instrumentation Command-line (WMIC) executable, specifically targeted at detecting instances where a process involves WMIC.exe with the command line containing "call" and "uninstall". The rule extracts data from process creation logs, focusing on the command line parameters and executable image details, making it crucial for tracking potentially malicious actions that could indicate untrusted program removal. This activity may be associated with a malicious actor attempting to disable protective software or other critical applications within an environment. This rule aligns with the MITRE ATT&CK technique T1047, which emphasizes commands that can be used to uninstall software on the system, indicating execution-driven actions by adversaries to modify the system's security posture.
  ### Investigation Steps
  - **Verify the Alert**: Check the EDR console for associated alerts related to the process `WMIC.exe` and confirm the command line parameters match the criteria set in the detection rule.
  - **Review Process History**: In Windows Event Logs and EDR, analyze the process creation events surrounding `WMIC.exe` to identify any suspicious parent processes or additional executables invoked before and after the command.
  - **Correlate with Other Logs**: Utilize firewall and proxy logs to look for outbound connections made by the system during the time of uninstallation; this may indicate further malicious behavior or data exfiltration.
  - **Assess Impact**: Investigate the applications that were uninstalled to evaluate their criticality to the environment and assess any potential risk posed by their removal.
  ### Prioritization
  The severity level is marked as medium due to the potential risk unauthorized uninstallation poses to system integrity and security. This could indicate active efforts by an adversary to weaken defenses, particularly if critical security applications are targeted.
  ### Blind Spots and Assumptions
  This detection rule may not fire if the adversary employs alternative methods for application removal that do not utilize WMIC, such as direct manipulation of files or registry entries, or if the command line is obfuscated. Additionally, reliance on process creation logs assumes that logging is adequately configured and preserved; any gaps in logging configurations may lead to missed detections.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and clarity, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
