title: Modify Group Policy Settings
id: ada4b0c4-758b-46ac-9033-9004613a150d
related:
- id: b7216a7d-687e-4c8d-82b1-3080b2ad961f
  type: similar
status: test
description: Detect malicious GPO modifications can be used to implement many other
  malicious behaviors.
references:
- https://github.com/redcanaryco/atomic-red-team/blob/40b77d63808dd4f4eafb83949805636735a1fd15/atomics/T1484.001/T1484.001.md
author: frack113
date: 2022-08-19
tags:
- attack.defense-evasion
- attack.privilege-escalation
- attack.t1484.001
logsource:
  category: process_creation
  product: windows
detection:
  selection_reg:
  - Image|endswith: '\reg.exe'
  - OriginalFileName: 'reg.exe'
  selection_path:
    CommandLine|contains: '\SOFTWARE\Policies\Microsoft\Windows\System'
  selection_key:
    CommandLine|contains:
    - GroupPolicyRefreshTimeDC
    - GroupPolicyRefreshTimeOffsetDC
    - GroupPolicyRefreshTime
    - GroupPolicyRefreshTimeOffset
    - EnableSmartScreen
    - ShellSmartScreenLevel
  condition: all of selection_*
falsepositives:
- Legitimate use
level: medium
notes: |
  ### Technical Context
  The "Modify Group Policy Settings" detection rule is designed to identify potentially malicious modifications to Group Policy settings using the Windows Registry. Specifically, it focuses on the execution of the `reg.exe` tool, often employed by attackers to manipulate Group Policy Object (GPO) settings, which can lead to various nefarious behaviors such as enabling unauthorized privilege escalation or disabling security features. The rule leverages process creation logs, inspecting command-line arguments that pertain to policy settings like `GroupPolicyRefreshTimeDC` and `EnableSmartScreen`, among others. By monitoring these parameters, the rule aims to detect attempts to modify critical GPO configurations, aligning with MITRE ATT&CK tactics for defense evasion (T1484.001) and privilege escalation. 
  ### Investigation Steps
  - **Review Process Creation Logs:** Inspect the `process_creation` logs in your EDR to identify instances of `reg.exe` execution, focusing on the command-line parameters used during its invocation.
  - **Analyze Registry Changes:** Utilize Windows Security logs to track any registry modifications associated with policy settings that may indicate unauthorized changes.
  - **Cross-Reference with Other Logs:** Check other relevant telemetry sources, such as Sysmon logs for network connections or file access, to uncover any additional malicious activity related to the detected process.
  - **Assess User Context:** Determine the user account associated with the GPO modification attempt. Evaluate if this account had legitimate reasons for changing group policy settings or if unusual behavior is evident.
  ### Prioritization
  This alert is classified as medium severity due to the potential for misuse of GPO modifications, which could lead to significant security risks, including privilege escalation and wider system compromise. Timely investigation is crucial to mitigate any long-term impacts on the organization’s security posture.
  ### Blind Spots and Assumptions
  This detection rule may not fire in the event that an adversary uses alternate methods to modify group policies, such as employing PowerShell scripts or leveraging built-in Windows administrative tools that do not require direct interaction with `reg.exe`. Additionally, legitimate administrative actions can produce false positives; understanding the context of user actions is essential for accurate detection. Engineers should also consider the possibility of changes being executed in a less detectable manner, such as using scheduled tasks or other background processes.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
