title: Sysmon Configuration Update
id: 87911521-7098-470b-a459-9a57fc80bdfd
status: test
description: Detects updates to Sysmon's configuration. Attackers might update or
  replace the Sysmon configuration with a bare bone one to avoid monitoring without
  shutting down the service completely
references:
- https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-03-09
modified: 2024-03-13
tags:
- attack.defense-evasion
- attack.t1562.001
logsource:
  category: process_creation
  product: windows
detection:
  selection_pe:
  - Image|endswith:
    - \Sysmon64.exe
    - \Sysmon.exe
  - Description: 'System activity monitor'
  selection_cli:
    CommandLine|contains|windash: '-c'
  condition: all of selection_*
falsepositives:
- Legitimate administrators might use this command to update Sysmon configuration.
level: medium
notes: |
  ### Technical Context
  The "Sysmon Configuration Update" detection rule targets modifications made to the Sysmon (System Monitor) configuration, specifically focusing on changes executed through the Sysmon executable. Attackers may attempt to circumvent detection by replacing or altering the Sysmon configuration to minimize monitoring capabilities of the system while keeping the service operational. The rule looks for process creation events where the image path ends with `Sysmon64.exe` or `Sysmon.exe`, along with command-line arguments that indicate a configuration change using the `-c` parameter. This detection is relevant as it aligns with the MITRE ATT&CK technique `T1562.001`, which pertains to defense evasion methods. Monitoring of Sysmon's behavior through Windows process creation logs provides vital telemetry for identifying potential unauthorized adjustments.
  ### Investigation Steps
  - **Verify Alert Source:** Correlate the alert with Windows Event Logs for process creation (Event ID 4688) to confirm that a legitimate user or an automated script executed a Sysmon configuration update.
  - **Examine Command-line Arguments:** Review the command-line parameters associated with the process creation to determine if the update was legitimate (e.g., by a trusted administrator) or indicative of unauthorized activity.
  - **Check for Anomalous Behavior:** Utilize EDR (Endpoint Detection and Response) tools to inspect surrounding processes and activities that occurred before and after the Sysmon update to identify any malicious behavior or persistence mechanisms.
  - **Evaluate Sysmon Configuration:** Extract and analyze the current Sysmon configuration to evaluate its completeness and whether it was altered to eliminate critical logging features, thereby assessing the effectiveness of monitoring post-update.
  ### Prioritization
  The severity level for this alert is categorized as medium because while legitimate administrative actions can cause similar alerts, unauthorized configuration changes typically indicate potential compromises aimed at evading detection mechanisms—a significant concern for the security posture of the enterprise.
  ### Blind Spots and Assumptions
  This detection rule may not trigger in cases where Sysmon has been completely uninstalled or when the attacker has leveraged administrative privileges to bypass logging altogether. Additionally, if an authorized user conducts the configuration change but does not follow proper procedures, it may lead to false positives. Adversaries may also alter their tactics to avoid scenarios that would trigger this detection, thus emphasizing the need for a holistic monitoring approach alongside this specific rule.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
