title: Security Support Provider (SSP) Added to LSA Configuration
id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
status: test
description: |
  Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
references:
- https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
- https://github.com/EmpireProject/Empire/blob/08cbd274bef78243d7a8ed6443b8364acd1fc48b/data/module_source/persistence/Install-SSP.ps1#L157
author: iwillkeepwatch
date: 2019-01-18
modified: 2022-08-09
tags:
- attack.persistence
- attack.t1547.005
logsource:
  category: registry_event
  product: windows
detection:
  selection:
    TargetObject|endswith:
    - '\Control\Lsa\Security Packages'
    - '\Control\Lsa\OSConfig\Security Packages'
  filter_main_msiexec:
    Image:
    - 'C:\Windows\system32\msiexec.exe'
    - 'C:\Windows\syswow64\MsiExec.exe'
  condition: selection and not 1 of filter_main_*
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  This Sigma rule is designed to detect the addition of a Security Support Provider (SSP) to the Local Security Authority (LSA) within the Windows registry. SSPs are dynamic-link libraries (DLLs) that can gain access to sensitive information, including encrypted and plaintext passwords stored in Windows. The detection mechanism focuses on specific registry keys, specifically `\Control\Lsa\Security Packages` and `\Control\Lsa\OSConfig\Security Packages`, where such additions typically occur. When an SSP is added, it can leverage existing vulnerabilities or malicious techniques to gain unauthorized access to critical system resources. This activity is categorized under the MITRE ATT&CK framework tactic of "Persistence" and specifically technique T1547.005, which involves embedding persistence mechanisms into the LSA.
  The relevant data sources for this detection include Windows registry event logs, which capture the modifications made to specific registry keys associated with the security configuration of the operating system. By monitoring these changes, security operations teams can identify potentially harmful activities aiming to maintain persistence on the affected system.
  ### Investigation Steps
  - **Check Registry Modifications:** Review recent changes made to the registry keys related to LSA Security Packages using a registry monitoring tool; look for unauthorized or suspicious DLL additions.
    
  - **Analyze EDR Alerts:** Utilize EDR tools to correlate the timing of the registry modification with any related processes that may indicate execution or exploitation, focusing on any remote command execution patterns.
  - **Review Process Creation Logs:** Search for process creation events around the time of the registry modification, especially for processes like `msiexec.exe`, to determine if any associated installations or modifications were initiated by potentially malicious actors.
  - **Assess System Behavior:** Investigate the affected system for unusual behavior or access patterns, particularly any attempts to retrieve or manipulate password data that may involve the newly added SSP.
  ### Prioritization
  Given the high severity level of this alert, it is critical to promptly investigate any instances of SSP additions as they can represent a significant security risk, potentially enabling attackers to exploit sensitive credential storage mechanisms within the environment.
  ### Blind Spots and Assumptions
  This detection rule may not fire in scenarios where the SSP is added via legitimate applications or trusted processes. Additionally, if the modification is made using direct registry access that does not generate standard logging events or if monitoring for specific registry changes is not enabled, the detection may be bypassed. It is also important to note that not all systems may utilize LSA to the same extent, leading to potential gaps in monitoring and detection.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
