title: Security Support Provider (SSP) Added to LSA Configuration
id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
status: test
description: |
  Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
references:
- https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
- https://github.com/EmpireProject/Empire/blob/08cbd274bef78243d7a8ed6443b8364acd1fc48b/data/module_source/persistence/Install-SSP.ps1#L157
author: iwillkeepwatch
date: 2019-01-18
modified: 2022-08-09
tags:
- attack.persistence
- attack.t1547.005
logsource:
  category: registry_event
  product: windows
detection:
  selection:
    TargetObject|endswith:
    - '\Control\Lsa\Security Packages'
    - '\Control\Lsa\OSConfig\Security Packages'
  filter_main_msiexec:
    Image:
    - 'C:\Windows\system32\msiexec.exe'
    - 'C:\Windows\syswow64\MsiExec.exe'
  condition: selection and not 1 of filter_main_*
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  This Sigma rule is designed to detect the addition of a Security Support Provider (SSP) to the Windows Local Security Authority (LSA) configuration. SSPs are dynamic-link libraries (DLLs) that can be added to the registry and gain access to sensitive information such as encrypted and plaintext passwords stored within Windows. The rule specifically looks for registry changes related to the paths `\Control\Lsa\Security Packages` and `\Control\Lsa\OSConfig\Security Packages`, indicating an attempted manipulation or persistence mechanism that can be employed by attackers. The detection relies on registry event logs, particularly focusing on changes made by `msiexec.exe`, a Windows utility typically used for installing applications, to ensure that these additions are not legitimate software installations.
  ### Investigation Steps
  - Conduct a query in the EDR platform for any recent registry modifications to the LSA configuration, specifically targeting the paths mentioned in the rule. 
  - Review process creation logs to determine if `msiexec.exe` was involved in the addition of the SSP and check for any suspicious command line arguments associated with these instances.
  - Analyze the associated network traffic through the NDR for any connections initiated around the time of the registry modification, which may indicate external command and control communications.
  - Search the SIEM for alerts related to the affected systems for other abnormal behaviors, including unusual logins or access to sensitive files, in order to assess the potential impact and scope of the incident.
