title: Potential Malicious AppX Package Installation Attempts
id: 09d3b48b-be17-47f5-bf4e-94e7e75d09ce
status: test
description: Detects potential installation or installation attempts of known malicious
  appx packages
references:
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
- https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
- https://forensicitguy.github.io/analyzing-magnitude-magniber-appx/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-01-11
modified: 2023-01-12
tags:
- attack.defense-evasion
logsource:
  product: windows
  service: appxdeployment-server
detection:
  selection:
    EventID:
    - 400
    - 401
        # Add more malicious package names
        # TODO: Investigate the packages here https://github.com/sophoslabs/IoCs/blob/master/Troj-BazarBackdoor.csv based on this report https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
    PackageFullName|contains: '3669e262-ec02-4e9d-bcb4-3d008b4afac9'
  condition: selection
falsepositives:
- Rare occasions where a malicious package uses the exact same name and version as
  a legtimate application
level: medium
notes: |
  ### Technical Context
  This detection rule aims to identify potential malicious attempts to install known harmful AppX packages on Windows systems. The rule focuses on specific Event IDs (400 and 401) generated by the AppX deployment service, which log events related to the installation of AppX packages. It particularly looks for the inclusion of a specific package identifier (`3669e262-ec02-4e9d-bcb4-3d008b4afac9`) that has been associated with malicious behavior. By leveraging logs from the AppX deployment service, the rule can effectively flag unauthorized installation attempts of these potentially harmful applications, providing an important layer of defense against threats like BazarLoader and Magniber malware variants.
  ### Investigation Steps
  - Review EDR logs for the endpoint where the alert was triggered, focusing on process creation events around the time of the installation attempt to identify any suspicious activity related to the AppX package.
  - Check the application and installation logs in the Windows Event Viewer to gather more context on the AppX deployment events, including the user account and execution context involved in the installation attempt.
  - Cross-reference the detected package name with threat intelligence sources, particularly focusing on known malicious AppX package lists to verify if it aligns with confirmed indicators of compromise.
  - Utilize the SIEM to correlate this event with any previous security alerts around the same timeframe, looking for patterns or recurring threats that may indicate a broader attack campaign.
