title: Uncommon AppX Package Locations
id: c977cb50-3dff-4a9f-b873-9290f56132f1
status: test
description: Detects an appx package added the pipeline of the "to be processed" packages
  which is located in uncommon locations
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
- https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
- https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-01-11
modified: 2024-12-25
tags:
- attack.defense-evasion
logsource:
  product: windows
  service: appxdeployment-server
detection:
  selection:
    EventID: 854
  filter_main_generic:
    Path|contains:
            # Paths can be written using forward slash if the "file://" protocol is used
    - 'C:\Program Files\WindowsApps\'
    - 'C:\Program Files (x86)\'
    - 'C:\Windows\SystemApps\'
    - 'C:\Windows\PrintDialog\'
    - 'C:\Windows\ImmersiveControlPanel\'
    - 'x-windowsupdate://'
    - 'file:///C:/Program%20Files'         # Also covers 'file:///C:/Program%20Files%20(x86)/'
  filter_main_specific:
    Path|contains:
    - 'https://statics.teams.cdn.live.net/'
    - 'https://statics.teams.cdn.office.net/'
    - 'microsoft.com'         # Example: https://go.microsoft.com/fwlink/?linkid=2160968
    - 'https://installer.teams.static.microsoft/'
  condition: selection and not 1 of filter_main_*
falsepositives:
- Unknown
level: medium
notes: |
  ### Technical Context
  The "Uncommon AppX Package Locations" detection rule is designed to identify potential threats involving Windows AppX packages being added from uncommon or suspicious locations. This rule looks for Event ID 854, which signifies an AppX package has been added to the processing pipeline. It specifically targets installation paths that are atypical or associated with known malicious activity, filtering out common trusted paths like `C:\Program Files\WindowsApps\` and `C:\Windows\SystemApps\`. Additionally, it checks for URLs that are commonly used in malicious activity surrounding Microsoft Teams installations. By monitoring the addition of these packages from specified locations, the rule aims to flag potentially malicious installations that could evade standard security controls.
  The primary technical data sources involved in this detection are Windows event logs related to application deployment, particularly focusing on AppX package operations. By analyzing this event data, SOC analysts can determine whether an application added through the pipeline could pose a security risk.
  ### Investigation Steps
  - Review the logs for Event ID 854 in the AppX deployment logs to identify the specific package that was added and the associated file path.
  - Use endpoint detection and response (EDR) tools to analyze the process tree and behavior of any executable related to the suspicious AppX package.
  - Check the network communications associated with the package using network detection and response (NDR) tools to identify any connections to known malicious domains.
  - Examine the application log files in Windows to understand when and how the package was installed, correlating this information with any other alerts or incidents within the environment.
