title: Suspicious AppX Package Locations
id: 5cdeaf3d-1489-477c-95ab-c318559fc051
status: test
description: Detects an appx package added the pipeline of the "to be processed" packages
  which is located in suspicious locations
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
- https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
- https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-01-11
tags:
- attack.defense-evasion
logsource:
  product: windows
  service: appxdeployment-server
detection:
  selection:
    EventID: 854
    Path|contains:
            # Paths can be written using forward slash if the "file://" protocol is used
    - 'C:\Users\Public\'
    - '/users/public/'
    - 'C:\PerfLogs\'
    - 'C:/perflogs/'
    - '\Desktop\'
    - '/desktop/'
    - '\Downloads\'
    - '/Downloads/'
    - 'C:\Windows\Temp\'
    - 'C:/Windows/Temp/'
    - '\AppdData\Local\Temp\'
    - '/AppdData/Local/Temp/'
  condition: selection
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  The "Suspicious AppX Package Locations" detection rule is designed to identify potential security threats tied to the deployment of AppX packages in atypical directories. These packages are part of the Windows app deployment system, and the rule focuses on events generated by the AppX Deployment Server (EventID 854) that indicate a package has been placed into certain locations typically associated with misuse or malware deployment. The locations monitored include public user folders, temporary directories, and common download locations, which could point to attempts to bypass security measures by hiding malicious AppX files in these accessible areas. By capturing these specific triggers, the rule helps to flag potentially malicious activity for further investigation.
  ### Investigation Steps
  - Review the AppX package details logged by analyzing EventID 854 in the Windows Event Logs to determine the origin and integrity of the package.
  - Use EDR tools to examine the associated process tree and command-line arguments of the AppX installation for any anomalous behavior or processes initiated by the package.
  - Check historical access logs from proxy or firewall systems for any suspicious IP communications originating from the infected host, particularly around the time of the warning event.
  - Scrutinize cloud logs (if applicable) for any unauthorized access or configuration changes, focusing on the user accounts involved in the deployments that triggered the alert.
