title: Suspicious Remote AppX Package Locations
id: 8b48ad89-10d8-4382-a546-50588c410f0d
status: experimental
description: |
  Detects an appx package added to the pipeline of the "to be processed" packages which was downloaded from a suspicious domain.
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
- https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
- https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-01-11
modified: 2024-08-22
tags:
- attack.defense-evasion
logsource:
  product: windows
  service: appxdeployment-server
detection:
  selection:
    EventID: 854
    Path|contains:
    - '.githubusercontent.com'               # Includes both gists and github repositories / Michael Haag (idea)
    - 'anonfiles.com'
    - 'cdn.discordapp.com'
    - 'ddns.net'
    - 'dl.dropboxusercontent.com'
    - 'ghostbin.co'
    - 'glitch.me'
    - 'gofile.io'
    - 'hastebin.com'
    - 'mediafire.com'
    - 'mega.nz'
    - 'onrender.com'
    - 'pages.dev'
    - 'paste.ee'
    - 'pastebin.com'
    - 'pastebin.pl'
    - 'pastetext.net'
    - 'privatlab.com'
    - 'privatlab.net'
    - 'send.exploit.in'
    - 'sendspace.com'
    - 'storage.googleapis.com'
    - 'storjshare.io'
    - 'supabase.co'
    - 'temp.sh'
    - 'transfer.sh'
    - 'trycloudflare.com'
    - 'ufile.io'
    - 'w3spaces.com'
    - 'workers.dev'
  condition: selection
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  The Sigma rule "Suspicious Remote AppX Package Locations" is designed to detect potentially malicious AppX packages that are processed through the Windows app deployment system. This rule focuses specifically on identifying package downloads from domains associated with malicious activity or known for distributing harmful software. By monitoring Windows EventID 854, which logs the addition of AppX packages to the processing pipeline, the detection relies on scrutinizing the path of the downloaded package for suspicious keywords characteristic of threat actor behavior. Data sources involved in this detection include AppX deployment server logs, specifically detailing the source of downloaded package files.
  This rule targets various domains that are often abused by cybercriminals, such as file-sharing websites and temporary file hosts. The use of domain filtering allows responders to quickly locate potentially harmful packages and initiate further investigation into the source and context of the download. As AppX packages can be a vector for malware payloads, the detection helps enhance security monitoring around application deployment on Windows environments.
  ### Investigation Steps
  - Investigate the AppX deployment logs in the SIEM to identify the specific EventID 854 occurrences and correlate these with timestamps and user activities.
  - Use EDR tools to examine the process trees related to the AppX package execution and look for any unusual behaviors or associated security alerts.
  - Review network traffic logs in the NGFW or NDR to assess communication with the suspicious domains, checking for outbound connections that may indicate data exfiltration or command-and-control activities.
  - Query the cloud logs, if applicable, to find related activities or additional context around the accounts and IP addresses involved in downloading the suspicious AppX packages.
