title: UAC Bypass Using MSConfig Token Modification - File
id: 41bb431f-56d8-4691-bb56-ed34e390906f
status: test
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
references:
- https://github.com/hfiref0x/UACME
author: Christian Burkard (Nextron Systems)
date: 2021-08-30
modified: 2022-10-09
tags:
- attack.defense-evasion
- attack.privilege-escalation
- attack.t1548.002
logsource:
  category: file_event
  product: windows
detection:
  selection:
    TargetFilename|startswith: 'C:\Users\'
    TargetFilename|endswith: '\AppData\Local\Temp\pkgmgr.exe'
  condition: selection
falsepositives:
- Unknown
level: high
notes: |
  n
  ### Technical Context
  This detection rule identifies potential user account control (UAC) bypass attempts through the modification of MSConfig using a malicious package manager executable (`pkgmgr.exe`). The rule focuses on the file events associated with Windows file operations, monitoring for specific patterns that indicate unauthorized access or manipulation of sensitive configuration files. By observing the target filename, the rule detects if the executable is being modified or executed from the "Temp" directory within a user's AppData. Such activities often indicate an attempt to elevate privileges and gain additional access within a system, aligning with the MITRE ATT&CK tactics of Defense Evasion and Privilege Escalation, specifically the technique T1548.002.
  ### Investigation Steps
  - **Check EDR Alerts:** Review EDR alerts related to the process creation of `pkgmgr.exe` for additional context on its execution and any associated processes to assess behavior and legitimacy.
  - **Analyze File Access:** Examine file access logs to ascertain how and when `pkgmgr.exe` was created, modified, or executed, and identify any patterns of suspicious activity leading up to the alert.
  - **Inspect System Logs:** Review Windows Security Logs for user account actions and potential unauthorized privilege escalations linked to this execution to verify if UAC was bypassed successfully.
  - **Network Traffic Analysis:** Conduct an analysis of outbound network connections related to the execution of `pkgmgr.exe` to determine if there were any data exfiltration attempts or communication with known malicious infrastructures.
  ### Prioritization
  The severity level is classified as high due to the potential for significant damage stemming from privileged actions taken by adversaries, which can lead to unauthorized access to sensitive systems and data.
  ### Blind Spots and Assumptions
  This rule may not fire in scenarios where the attacker employs different methodologies for UAC bypass that do not involve the specific `pkgmgr.exe` file or where the Temp folder is not utilized. Additionally, if the telemetry for file events is not comprehensively monitored, legitimate usage might be missed. Adversaries can bypass detection by utilizing different file names or locations to evade this rule. Analysts should remain vigilant and consider additional indicators of compromise (IoCs) when investigating related incidents.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
