title: Winget Admin Settings Modification
id: 6db5eaf9-88f7-4ed9-af7d-9ef2ad12f236
status: test
description: Detects changes to the AppInstaller (winget) admin settings. Such as
  enabling local manifest installations or disabling installer hash checks
references:
- https://github.com/nasbench/Misc-Research/tree/b9596e8109dcdb16ec353f316678927e507a5b8d/LOLBINs/Winget
- https://github.com/microsoft/winget-cli/blob/02d2f93807c9851d73eaacb4d8811a76b64b7b01/src/AppInstallerCommonCore/Public/winget/AdminSettings.h#L13
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-04-17
modified: 2023-08-17
tags:
- attack.defense-evasion
- attack.persistence
logsource:
  product: windows
  category: registry_set
detection:
  selection:
    Image|endswith: '\winget.exe'
    TargetObject|startswith: '\REGISTRY\A\'
    TargetObject|endswith: '\LocalState\admin_settings'
  condition: selection
falsepositives:
- The event doesn't contain information about the type of change. False positives
  are expected with legitimate changes
level: low
notes: |
  ### Technical Context
  The "Winget Admin Settings Modification" detection rule is designed to monitor and identify unauthorized changes to the AppInstaller (winget) administrative settings within a Windows environment. The rule specifically looks for modifications to the registry keys pertaining to local manifest installations and installer hash checks, which can be indicative of attempts to bypass security measures or implement unauthorized software installation processes. These changes can be leveraged by adversaries to maintain persistence through unauthorized manipulation of software installation settings. 
  The rule leverages Windows registry logging, specifically looking at changes made to the `\LocalState\admin_settings` area of the registry. The data sources involved primarily include Windows Security and System logs, which capture registry change events and provide the context necessary for investigations. This aligns with the MITRE ATT&CK techniques for defense evasion (T1203) and persistence (T1050).
  ### Investigation Steps
  - **Analyze Event Logs:** Review the Windows Security and System event logs corresponding to the detected registry key changes for additional context, such as timestamps and the user or process responsible for the modification.
  - **Check Process Creation:** Utilize EDR tools to examine the process creation logs around the time of the registry change to determine if `winget.exe` was executed and whether it was initiated by a known or authorized user.
  - **Cross-Verify with System State:** Use the command-line to extract current winget configuration settings and compare them against baseline configurations to identify any unauthorized configurations.
  - **Audit User Permissions:** Investigate user accounts that have permissions to modify registry settings to ensure that only authorized personnel have the capability to perform such changes, potentially identifying any compromised accounts.
  ### Prioritization
  This alert has been classified as low severity due to the potential for benign changes occurring in environments where administrative adjustments are routine. However, sustained monitoring is still necessary, as unauthorized modifications to winget settings could indicate larger security concerns.
  ### Blind Spots and Assumptions
  This rule assumes that changes to the specific registry keys are made through direct manipulation, and may not capture alterations made via other means, such as group policies or through the use of scripts that do not utilize `winget.exe`. There may also be legitimate administrative activities leading to false positives, which could obscure true threats. An adversary could potentially defeat this detection by employing techniques to modify registry settings without triggering observable `winget.exe` activity.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
