title: Disable Privacy Settings Experience in Registry
id: 0372e1f9-0fd2-40f7-be1b-a7b2b848fa7b
status: test
description: Detects registry modifications that disable Privacy Settings Experience
references:
- https://github.com/redcanaryco/atomic-red-team/blob/9e5b12c4912c07562aec7500447b11fa3e17e254/atomics/T1562.001/T1562.001.md
author: frack113
date: 2022-10-02
modified: 2023-08-17
tags:
- attack.defense-evasion
- attack.t1562.001
logsource:
  category: registry_set
  product: windows
detection:
  selection:
    TargetObject|endswith: '\SOFTWARE\Policies\Microsoft\Windows\OOBE\DisablePrivacyExperience'
    Details: 'DWORD (0x00000000)'
  condition: selection
falsepositives:
- Legitimate admin script
level: medium
notes: |
  ### Technical Context
  This detection rule is designed to identify unauthorized modifications made to the Windows Registry, specifically targeting the privacy settings related to the Out-of-Box Experience (OOBE). The rule looks for changes that set the `DisablePrivacyExperience` DWORD to `0` under the registry path `SOFTWARE\Policies\Microsoft\Windows\OOBE`. This modification can be an indication of attempts to evade security measures, thereby falling under the MITRE ATT&CK framework tactic of Defense Evasion, specifically the technique T1562.001 (Impair Defenses). The primary data source for this rule is the registry logs generated by Windows, which captures changes made to the registry hive.
  ### Investigation Steps
  - **Verify Registry Modification:** Check the Windows Registry to confirm the presence of the registry key and value change at the specified path. Assess the timestamps and user accounts associated with these modifications to establish their legitimacy.
  - **Review User Activity:** Utilize EDR tools to analyze the user activity leading up to the registry change. Examine account authentication logs, process creation logs, and other related telemetry to identify unusual behavior by the user account involved.
  - **Check for Scripts or Automation:** Investigate if the detected change was triggered by legitimate administrative scripts or deployment tools including group policies. This can help in differentiating between benign and potentially malicious activity.
  - **Monitor for Related Alerts:** Review the SIEM and EDR systems for any other alerts or activities associated with the affected system around the same timestamp. Look for other indicators of compromise that may point to broader exploitation efforts.
  ### Prioritization
  The severity level of this alert is medium due to the potential for it to indicate a deliberate attempt to disable critical privacy and security features on Windows systems, which could facilitate further malicious activity.
  ### Blind Spots and Assumptions
  This rule may not fire if the registry modification is made in a manner that does not utilize traditional methods, such as through an in-memory exploit or when the value was already set to `0`. Additionally, legitimate administrative actions may trigger false positives if not appropriately assessed. It is assumed that all changes are logged correctly; if logging is turned off or malfunctioning, detection efforts may be rendered ineffective. Adversaries could also utilize techniques to obfuscate such changes, like altering user rights or using alternate scripting methods.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
