title: New Application in AppCompat
id: 60936b49-fca0-4f32-993d-7415edcf9a5d
status: test
description: A General detection for a new application in AppCompat. This indicates
  an application executing for the first time on an endpoint.
references:
- https://github.com/OTRF/detection-hackathon-apt29/issues/1
- https://github.com/OTRF/ThreatHunter-Playbook/blob/2d4257f630f4c9770f78d0c1df059f891ffc3fec/docs/evals/apt29/detections/1.A.1_DFD6A782-9BDB-4550-AB6B-525E825B095E.md
author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
date: 2020-05-02
modified: 2023-08-17
tags:
- attack.execution
- attack.t1204.002
logsource:
  product: windows
  category: registry_set
detection:
  selection:
    TargetObject|contains: '\AppCompatFlags\Compatibility Assistant\Store\'
  condition: selection
falsepositives:
- This rule is to explore new applications on an endpoint. False positives depends
  on the organization.
- Newly setup system.
- Legitimate installation of new application.
level: informational
notes: |
  ### Technical Context
  The Sigma rule "New Application in AppCompat" is designed to detect the execution of new applications on a Windows endpoint by monitoring entries in the Windows registry. Specifically, it focuses on registry modifications under the key `\AppCompatFlags\Compatibility Assistant\Store\`, which indicates that an application is being executed for the first time. This rule leverages Windows registry logs as a key data source, providing insights into application behaviors and potential anomalies. As software installations can often invoke malicious code, the detection of new entries in the AppCompat flags can signal either legitimate updates or the potential for exploitation. The rule falls under the MITRE ATT&CK tactic of "Execution" and the technique T1204.002 (Malicious File Execution).
  ### Investigation Steps
  - **Verify Application Integrity:** Validate the newly detected application against known good hashes using your EDR or antivirus solutions to ascertain if it is a legitimate application.
  - **Review Process Creation Logs:** Check process creation events around the same time as the registry modification to identify the context in which the application was executed and any supporting processes involved.
  - **Analyze Network Activity:** Investigate any network connections initiated by the newly detected application using EDR or Network Detection and Response (NDR) tools to determine if unexpected external communication is occurring.
  - **Consult with Asset Inventory:** Review asset inventory and installation records to confirm whether the application was authorized and properly deployed within the organization’s policies.
  ### Prioritization
  This alert is classified as informational, indicating that while the detection of a new application in AppCompat may warrant investigation, it does not immediately point to malicious activity. This categorization allows SOC analysts to assess the context without alarm, focusing on potential risks associated with application changes.
  ### Blind Spots and Assumptions
  This rule may not trigger if applications are executed without modifying the AppCompatFlags registry key, such as through direct command line executions or bypass techniques. Additionally, environments that frequently deploy new software may experience higher false positives, leading to potential oversight in actual risky behaviors. Engineers should consider that legitimate updates and system setups could lead to numerous alerts, thus requiring contextual analysis to discern threat from benign activity.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and clarity, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
