title: Outlook Security Settings Updated - Registry
id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
related:
- id: a166f74e-bf44-409d-b9ba-ea4b2dd8b3cd     # EnableUnsafeClientMailRules
  type: similar
status: test
description: Detects changes to the registry values related to outlook security settings
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1137/T1137.md
- https://learn.microsoft.com/en-us/outlook/troubleshoot/security/information-about-email-security-settings
author: frack113
date: 2021-12-28
modified: 2023-08-17
tags:
- attack.persistence
- attack.t1137
logsource:
  category: registry_set
  product: windows
detection:
  selection:
    TargetObject|contains|all:
    - '\SOFTWARE\Microsoft\Office\'
    - '\Outlook\Security\'
  condition: selection
falsepositives:
- Administrative activity
level: medium
notes: |
  ### Technical Context
  This Sigma rule is designed to detect unauthorized changes to the security settings of Microsoft Outlook by monitoring specific Windows registry modifications. The detection focuses on registry paths that are pertinent to Outlook's security settings (specifically under `SOFTWARE\Microsoft\Office\Outlook\Security`). Investigations into these changes are critical, as they could indicate tampering intended to bypass security measures within Outlook, potentially allowing for malicious email interactions or the execution of harmful scripts. The rule is aligned with the MITRE ATT&CK tactic of Persistence and the specific technique T1137, which pertains to the usage of registry modifications to maintain persistence on a compromised system.
  To identify these changes, the rule relies on telemetry from the Windows Registry Set logs. By monitoring the actions that modify registry keys, analysts can be alerted to potentially malicious scripts or tools changing the Outlook security configurations without appropriate administrative permissions.
  ### Investigation Steps
  - **Examine Registry Changes:** Review the specific timestamps when the registry changes were detected, using registry monitoring tools or direct registry access to inspect values at `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Outlook\Security`.
  - **Verify User Activity:** Check Windows Security Event Logs for user authentication events around the time of the registry modification. This helps assess if the changes correlate with legitimate administrative tasks or if they are indicators of malicious activity.
  - **Analyze EDR Alerts:** Use endpoint detection and response (EDR) tools to investigate the associated processes active during the time of the registry change. Look for any unusual or unrecognized applications that may have performed the modification.
  - **Query Logs for Related Activity:** Utilize SIEM or cloud logs to examine any email clients' activity or related events to detect if there are anomalous email transmissions or behaviors subsequent to the registry changes.
  ### Prioritization
  The severity level for this alert is categorized as medium due to its implications for email security configurations, which can expose an organization to phishing and other malicious email threats if altered without authorization.
  ### Blind Spots and Assumptions
  This rule may not fire in situations where changes to the registry occur through legitimate administrative operations, potentially leading to false positive alerts. Additionally, if an adversary has obtained administrative privileges, they may manipulate settings undetected, allowing them to bypass this detection mechanism. It assumes that sufficient logging is enabled for the registry and that the monitoring tools are properly configured to recognize changes to these specific paths.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
