title: Windows Defender Exploit Guard Tamper
id: a3ab73f1-bd46-4319-8f06-4b20d0617886
status: test
description: |
  Detects when someone is adding or removing applications or folders from exploit guard "ProtectedFolders" or "AllowedApplications"
references:
- https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/windows-10-controlled-folder-access-event-search/ba-p/2326088
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-08-05
modified: 2022-12-06
tags:
- attack.defense-evasion
- attack.t1562.001
logsource:
  product: windows
  service: windefend
detection:
  allowed_apps_key:
    EventID: 5007     # The antimalware platform configuration changed.
    NewValue|contains: '\Windows Defender\Windows Defender Exploit Guard\Controlled
      Folder Access\AllowedApplications\'
  allowed_apps_path:
    NewValue|contains:
            # Add more paths you don't allow in your org
    - '\Users\Public\'
    - '\AppData\Local\Temp\'
    - '\Desktop\'
    - '\PerfLogs\'
    - '\Windows\Temp\'
  protected_folders:
    EventID: 5007     # The antimalware platform configuration changed.
        # This will trigger on any folder removal. If you experience FP's then add another selection with specific paths
    OldValue|contains: '\Windows Defender\Windows Defender Exploit Guard\Controlled
      Folder Access\ProtectedFolders\'
  condition: all of allowed_apps* or protected_folders
falsepositives:
- Unlikely
level: high
notes: |
  ### Technical Context
  The "Windows Defender Exploit Guard Tamper" rule identifies suspicious modifications to the Windows Defender Exploit Guard's exploit protection settings, specifically focusing on changes to allowed applications and protected folders. The detection leverages Windows Event ID 5007, which signifies configuration changes within the antimalware platform. By monitoring the `NewValue` field for entries related to "AllowedApplications" and "ProtectedFolders," the rule can alert on unauthorized attempts to add or remove entries that could potentially bypass the protection mechanisms intended to safeguard critical folders from tampering by malware or unauthorized users. This falls under the MITRE ATT&CK tactic of "Defense Evasion," specifically the technique T1562.001, which refers to disabling or circumventing security controls.
  ### Investigation Steps
  - **Investigate Event Logs:** Check Windows Event Logs for Event ID 5007, focusing on relevant changes to the AllowedApplications and ProtectedFolders settings. Look for unusual entries that were not initiated by authorized administrative actions.
  - **Assess User Activity:** Review user activity around the time of the detected changes by analyzing user login logs and network activities. Identify whether the account involved had valid access or was compromised.
  - **Analyze EDR Alerts:** Utilize EDR tools to detect any suspicious process creations or file modifications that correspond with the event timestamps. Look for unusual behavior that may indicate an active threat.
  - **Correlate with AV/Proxy Logs:** Examine logs from AV and Proxy systems to identify any blocked threats or unusual outbound connections that may indicate a larger compromise. Determine if any blocked applications were added to the allowed list.
  ### Prioritization
  This alert is categorized as high severity due to the potential implications of unauthorized changes in protective configurations, which could expose sensitive data to malicious exploitation.
  ### Blind Spots and Assumptions
  This rule may not fire in environments where Windows Defender's tampering protection is not enabled or where the monitoring of Event ID 5007 is not configured. It assumes regular and authorized administrative actions, thus changes made via legitimate administrative updates may not trigger alerts. Additionally, if an adversary uses low-profile techniques or legitimate credentials to make these changes, the detection may be bypassed, leading to potential blind spots in visibility.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
