title: Windows Defender Exclusions Added
id: 1321dc4e-a1fe-481d-a016-52c45f0c8b4f
status: stable
description: Detects the Setting of Windows Defender Exclusions
references:
- https://twitter.com/_nullbind/status/1204923340810543109
author: Christian Burkard (Nextron Systems)
date: 2021-07-06
modified: 2022-12-06
tags:
- attack.defense-evasion
- attack.t1562.001
logsource:
  product: windows
  service: windefend
detection:
  selection:
    EventID: 5007     # The antimalware platform configuration changed.
    NewValue|contains: '\Microsoft\Windows Defender\Exclusions'
  condition: selection
falsepositives:
- Administrator actions
level: medium
notes: |
  ### Technical Context
  The Sigma rule titled "Windows Defender Exclusions Added" is designed to monitor and detect configuration changes in Windows Defender, specifically the addition of exclusions. Exclusions in Windows Defender allow processes, files, folders, or IP addresses to be ignored by the antivirus, potentially facilitating adversarial activities by evading detection. The rule is triggered by Windows event ID 5007, which indicates a change in the antimalware platform's configuration. When the new value for this event contains the path `\Microsoft\Windows Defender\Exclusions`, the rule activates. The data sources for this detection primarily come from Windows Security logs. This activity aligns with the MITRE ATT&CK tactic of Defense Evasion, specifically technique T1562.001, which involves manipulating security software settings to evade detection.
  ### Investigation Steps
  - **Review the Event Log:** Check Windows Security Event Logs for Event ID 5007 to confirm the exact timing and user account involved in modifying the Windows Defender exclusions.
    
  - **Correlate with User Activity:** Utilize endpoint detection and response (EDR) tools to correlate the event with user activity. Review recent user actions prior to the event to determine if any abnormal behaviors were observed.
  - **Inspect Exclusions List:** Analyze the current exclusions list in Windows Defender to determine what has been added, and check if any of the excluded items are suspicious or known malicious indicators.
  - **Check for Related Alerts:** Search for any other related alerts or anomalies occurring around the same time to assess if this is part of a larger potential compromise or abnormal behavior pattern.
  ### Prioritization
  This alert is categorized as medium severity due to its potential implications for security posture; the creation of exclusions can indicate an attempt to bypass malware detection, which warrants further investigation but may not always signify a critical incident.
  ### Blind Spots and Assumptions
  One significant blind spot is that legitimate administrator actions might trigger this rule, leading to false positives. Additionally, malware may evade detection by utilizing other means to manipulate Defender exclusions or by using other techniques that do not generate an Event ID 5007. It is also assumed that logging is properly configured, and older versions of the operating system or misconfigurations may not generate the necessary logs to trigger the rule. Understanding these assumptions can help detection engineers refine monitoring strategies and adjust for potential evasion scenarios.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
