title: Windows Defender Submit Sample Feature Disabled
id: 91903aba-1088-42ee-b680-d6d94fe002b0
related:
- id: 1321dc4e-a1fe-481d-a016-52c45f0c8b4f
  type: similar
- id: a3ab73f1-bd46-4319-8f06-4b20d0617886
  type: similar
- id: 801bd44f-ceed-4eb6-887c-11544633c0aa
  type: similar
status: stable
description: Detects disabling of the "Automatic Sample Submission" feature of Windows
  Defender.
references:
- https://learn.microsoft.com/en-us/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide
- https://bidouillesecurity.com/disable-windows-defender-in-powershell/#DisableAntiSpyware
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-12-06
tags:
- attack.defense-evasion
- attack.t1562.001
logsource:
  product: windows
  service: windefend
detection:
  selection:
    EventID: 5007     # The antimalware platform configuration changed.
    NewValue|contains: '\Real-Time Protection\SubmitSamplesConsent = 0x0'
  condition: selection
falsepositives:
- Administrator activity (must be investigated)
level: low
notes: |
  ### Technical Context
  This Sigma rule is designed to detect when the "Automatic Sample Submission" feature of Windows Defender is disabled, which is a behavior often associated with attempts to evade detection by security tools. The rule specifically monitors Windows Event Logs for EventID 5007, indicating a change in the configuration of the antimalware platform. The relevant log checks for a new value that signifies consent to submit samples has been set to '0', indicating that submissions are disabled. This action can be part of a broader adversarial tactic aimed at obstructing security efforts (MITRE ATT&CK Tactic: Defense Evasion, Technique: T1562.001). 
  Understanding the implications of this action is crucial; when sample submissions are disabled, it significantly hinders the effectiveness of endpoint protection mechanisms, potentially enabling malicious activities without alerting security monitoring systems. Therefore, timely investigation when this alert is triggered is essential for ensuring the integrity of the security posture within an organization.
  ### Investigation Steps
  - **Check Event Logs:** Review Windows Event Logs for EventID 5007 to confirm the configuration change and gather pertinent details about the affected system and user involved.
  - **Examine EDR Alerts:** Utilize your Endpoint Detection and Response (EDR) tool to investigate any related alerts that may coincide with the configuration change, as they may provide additional insight into associated activities or threats.
  - **Review Administrator Actions:** Since disabling such features may involve legitimate administrator activities, cross-reference the time of the event with administrator account actions to ascertain whether the change was authorized or malicious.
  - **Assess Related Security Tools:** Evaluate other security solutions (for example, AV logs or security policies) to determine if any anomalies or override conditions may have contributed to the disabling of the automatic submission feature.
  ### Prioritization
  While this alert is classified as low severity, it is an important indicator of potential security evasion tactics that require prompt investigation, as disabling automatic sample submissions can facilitate undetected malicious activity.
  ### Blind Spots and Assumptions
  This rule may not trigger if the configuration change is made through legitimate administrative actions or if there are discrepancies in logging due to misconfigured or disabled logging policies. Additionally, if an attacker uses an alternative method to disable sample submission that does not generate an EventID 5007, the rule would not detect it. Recognizing that not every change will be malicious is essential, and thorough investigation is warranted to differentiate between legitimate administrative actions and potential compromise.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
