title: Windows Defender Exploit Guard Tamper
id: a3ab73f1-bd46-4319-8f06-4b20d0617886
status: test
description: |
  Detects when someone is adding or removing applications or folders from exploit guard "ProtectedFolders" or "AllowedApplications"
references:
- https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/windows-10-controlled-folder-access-event-search/ba-p/2326088
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-08-05
modified: 2022-12-06
tags:
- attack.defense-evasion
- attack.t1562.001
logsource:
  product: windows
  service: windefend
detection:
  allowed_apps_key:
    EventID: 5007     # The antimalware platform configuration changed.
    NewValue|contains: '\Windows Defender\Windows Defender Exploit Guard\Controlled
      Folder Access\AllowedApplications\'
  allowed_apps_path:
    NewValue|contains:
            # Add more paths you don't allow in your org
    - '\Users\Public\'
    - '\AppData\Local\Temp\'
    - '\Desktop\'
    - '\PerfLogs\'
    - '\Windows\Temp\'
  protected_folders:
    EventID: 5007     # The antimalware platform configuration changed.
        # This will trigger on any folder removal. If you experience FP's then add another selection with specific paths
    OldValue|contains: '\Windows Defender\Windows Defender Exploit Guard\Controlled
      Folder Access\ProtectedFolders\'
  condition: all of allowed_apps* or protected_folders
falsepositives:
- Unlikely
level: high
notes: |
  ### Technical Context
  This detection rule monitors modifications to the Windows Defender Exploit Guard settings, specifically tracking changes to the "ProtectedFolders" and "AllowedApplications" configurations. It identifies events where applications or folders are added or removed from these settings by analyzing Event ID 5007 logs, which indicate when the antimalware platform configuration has changed. It focuses on NewValue fields that contain paths related to allowed applications and disallowed directories, such as common user folders that could present vulnerabilities if exploited. By alerting on these changes, the rule helps identify potential tampering activities aimed at bypassing security measures designed to protect sensitive files and applications from unauthorized access.
  ### Investigation Steps
  - Check EDR logs for elevated administrative access or unauthorized user activity around the time of the alert to understand who made the configuration change.
  - Review Windows Defender logs for any unusual entries or behaviors preceding the configuration change, paying specific attention to potential malware interactions.
  - Examine file access logs or Proxy logs around the detected changes to determine if there were any suspicious activities related to the newly allowed applications or folders.
  - Conduct an inventory check of the applications currently installed on affected systems to ascertain whether they align with organizational policy and security guidelines.
