title: Invoke-Obfuscation RUNDLL LAUNCHER - Security
id: f241cf1b-3a6b-4e1a-b4f9-133c00dd95ca
related:
- id: 11b52f18-aaec-4d60-9143-5dd8cc4706b9
  type: derived
status: test
description: Detects Obfuscated Powershell via RUNDLL LAUNCHER
references:
- https://github.com/SigmaHQ/sigma/issues/1009     # (Task 23)
author: Timur Zinniatullin, oscd.community
date: 2020-10-18
modified: 2022-11-29
tags:
- attack.defense-evasion
- attack.t1027
- attack.execution
- attack.t1059.001
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
  selection:
    EventID: 4697
    ServiceFileName|contains|all:
    - 'rundll32.exe'
    - 'shell32.dll'
    - 'shellexec_rundll'
    - 'powershell'
  condition: selection
falsepositives:
- Unknown
level: medium
notes: |
  ### Technical Context
  This Sigma rule detects potential misuse of the `rundll32.exe` launcher to execute obfuscated PowerShell commands. The `rundll32.exe` process is often exploited by adversaries to execute malicious scripts without drawing attention. This detection leverages Windows Security event logs, specifically looking for Event ID 4697, which signifies the creation of a new service. The rule filters for service file names that include keywords such as `rundll32.exe`, `shell32.dll`, `shellexec_rundll`, and `powershell`, which together suggest an attempt to invoke obfuscated PowerShell commands. This activity is relevant to the MITRE ATT&CK tactics of Defense Evasion (T1027) and Execution (T1059.001), indicating an effort by attackers to remain undetected while executing potentially harmful scripts.
  ### Investigation Steps
  - **Correlate Events:** Review other relevant Windows Security logs around the time of the alert for additional Event IDs (such as 4688 for process creation) that could indicate the context in which `rundll32.exe` was invoked.
  - **Analyze Command-Line Arguments:** Use EDR tools to examine command-line arguments associated with the process to determine if they indicate malicious behavior or an unusual payload.
  - **Check Service Configuration:** Investigate the service that was created in the alert by examining its configuration settings, startup type, and associated user accounts using PowerShell or Service Control Manager (SCM).
  - **Cross-reference Threat Intelligence:** Use threat intelligence feeds to determine if the specific file names and behaviors observed in this alert have been associated with any known malware campaigns.
  ### Prioritization
  The severity of this alert is rated as medium due to the potential for using common Windows utilities to bypass security measures, indicating a moderate risk to the enterprise environment. Quick response is essential, as such activities often precede larger attack vectors.
  ### Blind Spots and Assumptions
  This rule may not fire under certain conditions, such as if the obfuscated PowerShell command is executed through methods other than service creation, or if the `rundll32.exe` process is used legitimately in the environment. Additionally, if logging for Event ID 4697 is not properly configured, the alert will not generate. Adversaries may employ techniques to modify or spoof the service's parameters to disguise malicious activity, reducing the effectiveness of this detection.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
