title: Invoke-Obfuscation Via Use MSHTA - Security
id: 9b8d9203-4e0f-4cd9-bb06-4cc4ea6d0e9a
related:
- id: 7e9c7999-0f9b-4d4a-a6ed-af6d553d4af4
  type: derived
status: test
description: Detects Obfuscated Powershell via use MSHTA in Scripts
references:
- https://github.com/SigmaHQ/sigma/issues/1009     # (Task31)
author: Nikita Nazarov, oscd.community
date: 2020-10-09
modified: 2022-11-29
tags:
- attack.defense-evasion
- attack.t1027
- attack.execution
- attack.t1059.001
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
  selection:
    EventID: 4697
    ServiceFileName|contains|all:
    - 'mshta'
    - 'vbscript:createobject'
    - '.run'
    - 'window.close'
  condition: selection
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  This detection rule identifies potentially malicious use of the Microsoft HTML Application (MSHTA) utility through obfuscated PowerShell scripts. MSHTA allows users to execute HTML applications, which can include scripts such as VBScript that may invoke command execution in an obfuscated manner. The rule specifically monitors Windows security log events (Event ID 4697) for indications that a service file linked to MSHTA contains certain keywords indicative of obfuscation techniques. These keywords include "vbscript:createobject," ".run," and "window.close." The presence of these terms suggests the likelihood of an attempt to evade security measures by executing hidden malicious commands, warranting further investigation.
  ### Investigation Steps
  - Utilize your EDR solution to search for the process creation logs associated with the Event ID 4697 identified in the alerts, focusing on the specific instances where MSHTA was invoked.
  - Analyze the command-line parameters of the detected processes to confirm the presence of scripts or commands that correlate with the identified obfuscation techniques, such as 'vbscript:createobject'.
  - Review proxy logs to detect any external connections initiated by the MSHTA process, which may indicate further malicious activity or data exfiltration attempts.
  - Examine any relevant logs from cloud platforms (AWS, GCP, Azure) for unauthorized access or unusual service activity that might correspond with the timing and context of the alert.
