title: Invoke-Obfuscation STDIN+ Launcher - Security
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
related:
- id: 72862bf2-0eb1-11eb-adc1-0242ac120002
  type: derived
status: test
description: Detects Obfuscated use of stdin to execute PowerShell
references:
- https://github.com/SigmaHQ/sigma/issues/1009      # (Task 25)
author: Jonathan Cheong, oscd.community
date: 2020-10-15
modified: 2022-11-29
tags:
- attack.defense-evasion
- attack.t1027
- attack.execution
- attack.t1059.001
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
  selection:
    EventID: 4697
    ServiceFileName|contains|all:
    - 'cmd'
    - 'powershell'
  selection2:
    ServiceFileName|contains:
    - '${input}'
    - 'noexit'
  selection3:
    ServiceFileName|contains:
    - ' /c '
    - ' /r '
  condition: all of selection*
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  This detection rule aims to identify potential misuse of PowerShell by leveraging obfuscation techniques through the use of standard input (stdin). The rule focuses on Event ID 4697 from Windows Security logs, which indicates system services being created. It specifically looks for service file names that contain 'cmd' or 'powershell', as well as command line parameters that may indicate obfuscated execution methods, such as using the '/c' or '/r' flags. By monitoring for these patterns, the rule can help uncover malicious activities that evade traditional security measures, leveraging recognized attack tactics such as defense evasion and execution methods associated with scripting languages, particularly PowerShell.
  ### Investigation Steps
  - Review the alerts generated by the detection rule in your SIEM platform to identify all instances of Event ID 4697 that match the detection criteria.
  - Utilize your EDR tool to inspect the process tree of the affected systems for any processes spawned by obfuscated commands, specifically looking for 'cmd' or 'powershell' executions.
  - Check the command-line parameters associated with the flagged events to determine if there are any malicious patterns or unexpected command executions that warrant further investigation.
  - Analyze network traffic logs from the NDR or NGFW to determine if any suspicious outbound connections were initiated by the identified 'cmd' or 'powershell' processes.
