title: Invoke-Obfuscation Obfuscated IEX Invocation - Security
id: fd0f5778-d3cb-4c9a-9695-66759d04702a
related:
- id: 51aa9387-1c53-4153-91cc-d73c59ae1ca9
  type: derived
status: test
description: Detects all variations of obfuscated powershell IEX invocation code generated
  by Invoke-Obfuscation framework from the code block linked in the references
references:
- https://github.com/danielbohannon/Invoke-Obfuscation/blob/f20e7f843edd0a3a7716736e9eddfa423395dd26/Out-ObfuscatedStringCommand.ps1#L873-L888
author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
date: 2019-11-08
modified: 2022-11-27
tags:
- attack.defense-evasion
- attack.t1027
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
  selection_eid:
    EventID: 4697
  selection_servicefilename:
  - ServiceFileName|re: '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\['
  - ServiceFileName|re: '\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\['
  - ServiceFileName|re: '\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\['
  - ServiceFileName|re: '\$env:ComSpec\[(\s*\d{1,3}\s*,){2}'
  - ServiceFileName|re: '\\*mdr\*\W\s*\)\.Name'
  - ServiceFileName|re: '\$VerbosePreference\.ToString\('
  - ServiceFileName|re: '\String\]\s*\$VerbosePreference'
  condition: all of selection_*
falsepositives:
- Unknown
level: high
notes: |
  n
  ### Technical Context
  The Sigma rule titled "Invoke-Obfuscation Obfuscated IEX Invocation" detects obfuscated PowerShell command invocations that utilize the Invoke-Obfuscation framework, which is commonly used by threat actors to evade detection and execute malicious payloads. The rule leverages the Windows Security Event Log with a specific focus on Event ID 4697, which relates to service configurations within the Windows environment. It systematically checks for known patterns in the `ServiceFileName` field, looking for variations of obfuscated PowerShell execution that are indicative of attempts to conceal malicious command execution. This detection is aligned with the MITRE ATT&CK techniques for Defense Evasion (T1027), which includes the use of obfuscated commands to bypass security measures.
  ### Investigation Steps
  - **Review Security Events:** Utilize the SIEM to filter for Event ID 4697 across the Windows Security logs to identify any instances of obfuscated PowerShell invocation.
  - **Correlate with Process Logs:** Cross-reference the findings with process creation logs to determine if the obfuscated commands resulted in any process executions and assess the nature of those processes using EDR tools.
  - **Analyze Network Connections:** Check for any network connections initiated by the identified processes to determine if further malicious communication or data exfiltration has occurred.
  - **Inspect User Context:** Investigate the user context under which the PowerShell commands were executed to identify any unauthorized access or anomalies in user behavior.
  ### Prioritization
  Given the high-severity level of this alert, any detection of obfuscated PowerShell IEX invocation suggests a potential immediate threat to the enterprise, warranting prompt investigation due to the high likelihood of malicious activity being present.
  ### Blind Spots and Assumptions
  This rule may not trigger if the obfuscation methods used do not match the specified regex patterns, allowing an adversary to customize their scripts beyond typical obfuscation techniques. Additionally, if security settings that generate Event ID 4697 are not enabled or properly configured on the host systems, legitimate activities may not be logged, leading to potential gaps in detection. It is assumed that defenders are monitoring environments where such activities commonly occur; however, limited visibility into non-Windows environments or highly compartmentalized systems could also impact detection efficacy.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
