title: ADCS Certificate Template Configuration Vulnerability with Risky EKU
id: bfbd3291-de87-4b7c-88a2-d6a5deb28668
status: test
description: Detects certificate creation with template allowing risk permission subject
  and risky EKU
references:
- https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
author: Orlinum , BlueDefenZer
date: 2021-11-17
modified: 2022-12-25
tags:
- attack.privilege-escalation
- attack.credential-access
logsource:
  product: windows
  service: security
  definition: Certificate services loaded a template would trigger event ID 4898 and
    certificate Services template was updated would trigger event ID 4899. A risk
    permission seems to be coming if template contain specific flag with risky EKU.
detection:
  selection10:
    EventID: 4898
    TemplateContent|contains:
    - '1.3.6.1.5.5.7.3.2'
    - '1.3.6.1.5.2.3.4'
    - '1.3.6.1.4.1.311.20.2.2'
    - '2.5.29.37.0'
  selection11:
    TemplateContent|contains: 'CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT'

  selection20:
    EventID: 4899
    NewTemplateContent|contains:
    - '1.3.6.1.5.5.7.3.2'
    - '1.3.6.1.5.2.3.4'
    - '1.3.6.1.4.1.311.20.2.2'
    - '2.5.29.37.0'
  selection21:
    NewTemplateContent|contains: 'CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT'

  condition: (selection10 and selection11) or (selection20 and selection21)
falsepositives:
- Administrator activity
- Proxy SSL certificate with subject modification
- Smart card enrollement
level: high
notes: |
  ### Technical Context
  This detection rule identifies potentially risky configurations in Active Directory Certificate Services (AD CS) by monitoring specific events related to certificate templates. By analyzing Windows Security event logs, specifically Event IDs 4898 and 4899, the rule looks for updates to certificate templates that include certain critical Extended Key Usage (EKU) Object Identifiers (OIDs) known to grant excessive permissions or that allow the subject to supply its own information. The presence of the flag `CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT` indicates that the end user can specify the certificate subject, which could facilitate unauthorized access if misconfigured. This rule is tied to the MITRE ATT&CK techniques related to Privilege Escalation and Credential Access, specifically focusing on the manipulation of certificate templates that may lead to security holes in the environment.
  ### Investigation Steps
  - **Verify Event Log Entries**: Check Windows Security logs for Event IDs 4898 and 4899 to confirm the generation of the alert and understand the context of the certificate template modification.
  - **Review Template Contents**: Analyze the specific certificate template being modified or created for risky EKUs and the `CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT` flag to determine the level of risk associated with the template configuration.
  - **Identify User Activity**: Investigate user activities and roles associated with the certificate creation/modification events to ensure legitimate administrative action and verify if any unauthorized user had the privileges.
  - **Monitor Network Connections**: Utilize EDR and network monitoring tools to track any suspicious activity related to the issuance of the certificates, such as unusual outbound connections to resources that use the certificates created.
  ### Prioritization
  This alert has been assigned a high severity level due to the potential for privilege escalation and credential theft when risky certificate templates are misconfigured or abused, which can significantly compromise the security posture of the enterprise.
  ### Blind spots and Assumptions
  There are several factors where this rule may not trigger. It assumes that the Windows Security logs are properly configured and monitored, and that the related Event IDs are not filtered or missing. Additionally, if an adversary executes legitimate administrative actions under their credentials, they may mask their malicious intent, leading to false negatives. Other assumptions include the availability of event logs and that any administrative work, such as smart card enrollment or valid proxy certificate actions, will not trip the alert and are correctly marked as false positives.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
