title: Invoke-Obfuscation STDIN+ Launcher - Security
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
related:
- id: 72862bf2-0eb1-11eb-adc1-0242ac120002
  type: derived
status: test
description: Detects Obfuscated use of stdin to execute PowerShell
references:
- https://github.com/SigmaHQ/sigma/issues/1009      # (Task 25)
author: Jonathan Cheong, oscd.community
date: 2020-10-15
modified: 2022-11-29
tags:
- attack.defense-evasion
- attack.t1027
- attack.execution
- attack.t1059.001
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
  selection:
    EventID: 4697
    ServiceFileName|contains|all:
    - 'cmd'
    - 'powershell'
  selection2:
    ServiceFileName|contains:
    - '${input}'
    - 'noexit'
  selection3:
    ServiceFileName|contains:
    - ' /c '
    - ' /r '
  condition: all of selection*
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  The detection rule for "Invoke-Obfuscation STDIN+ Launcher" primarily targets PowerShell-related obfuscation techniques, which are often employed by attackers to execute malicious commands in a stealthy manner. This rule specifically looks for Event ID 4697 in Windows Security logs, which indicates the "Service File Name" field containing certain keywords associated with command-line execution, such as 'cmd' and 'powershell'. Furthermore, it identifies the usage of the '/c' and '/r' flags that facilitate command execution in a one-liner format, which is often used in conjunction with obfuscation techniques to evade detection. The MITRE ATT&CK techniques referenced include T1027 (Obfuscated Files or Information) and T1059.001 (Command and Scripting Interpreter: Windows Command Shell). By correlating these indicators, this rule enables the identification of potential misuse of PowerShell and command-line interfaces to execute obfuscated commands.
  ### Investigation Steps
  - **Review Security Logs:** Check Windows Security logs for Event ID 4697 related to the detected alerts, and focus specifically on the 'ServiceFileName' to understand the context of the command execution.
  - **Analyze Process Activity:** Use EDR tools to analyze any associated process creation events. Identify parent-child process relationships to track the origin of the potentially malicious invocation.
  - **Inspect Command-Line Arguments:** Investigate the specific command-line parameters that were passed during the execution event. Look for common indicators of obfuscation or suspicious flags that may suggest malicious intent.
  - **Check for Anomalous Network Activity:** Use network logs to see if any connections were made by the process during its execution. Identify any unusual destinations or data exfiltration efforts indicative of a broader compromise.
  ### Prioritization
  This alert should be treated with high priority due to the potential for evading detection through obfuscation techniques which are commonly leveraged by advanced persistent threats (APTs) and other malicious actors. An immediate investigation is warranted to ascertain the nature of the PowerShell invocation and potential impact on the enterprise environment.
  ### Blind Spots and Assumptions
  This rule may not fire if the relevant auditing settings for Event ID 4697 are not enabled within the Windows Security configuration. Additionally, if an adversary employs custom obfuscation techniques not covered by the specified keywords or modifies command execution patterns (e.g., using alternative command shells), the rule may fail to detect these actions. Furthermore, in environments where PowerShell logging is disabled or insufficient, legitimate administrative activity could also be misclassified as benign, leading to false negatives.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
