title: ADCS Certificate Template Configuration Vulnerability
id: 5ee3a654-372f-11ec-8d3d-0242ac130003
status: test
description: Detects certificate creation with template allowing risk permission subject
references:
- https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
author: Orlinum , BlueDefenZer
date: 2021-11-17
modified: 2022-12-25
tags:
- attack.privilege-escalation
- attack.credential-access
logsource:
  product: windows
  service: security
  definition: Certificate services loaded a template would trigger event ID 4898 and
    certificate Services template was updated would trigger event ID 4899. A risk
    permission seems to be coming if template contain specific flag.
detection:
  selection1:
    EventID: 4898
    TemplateContent|contains: 'CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT'
  selection2:
    EventID: 4899
    NewTemplateContent|contains: 'CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT'
  condition: selection1 or selection2
falsepositives:
- Administrator activity
- Proxy SSL certificate with subject modification
- Smart card enrollement
level: low
notes: |
  ### Technical Context
  The "ADCS Certificate Template Configuration Vulnerability" detection rule aims to identify unauthorized or risky configurations in Active Directory Certificate Services (ADCS). Specifically, it looks for events related to certificate template creation and updates that include the flag `CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT`. When this specific flag is present, it suggests that the template allows users to specify the subject of the certificate, which poses a significant risk for unauthorized privilege escalation and credential access. The rule monitors Windows Security logs, particularly watching for Event ID 4898 (indicating a template has been created) and Event ID 4899 (indicating an existing template has been modified). This detection is associated with the MITRE ATT&CK tactics of Privilege Escalation (T1068) and Credential Access (T1552).
  ### Investigation Steps
  - **Review Event Logs:** Use Windows Security Event Logs to identify Event ID 4898 or 4899 and examine the details for the flagged templates. Look for unauthorized or unexpected changes made by users.
  - **Correlate with User Activity:** Cross-reference the log entries with user account activities in your SIEM to detect any abnormal administrative actions related to certificate templates.
  - **Investigate Relevant Certificates:** Check the impacted certificates linked to the templates for any unusual subject entries or permissions that may have been granted inadvertently or maliciously.
  - **Assess System Permissions:** Utilize EDR to monitor whether external entities are accessing or attempting to exploit the vulnerable certificate configurations and review permissions of the involved user accounts.
  ### Prioritization
  This alert is categorized as low severity, primarily due to the potential existence of benign administrator activities or legitimate configurations that invoke the same event IDs. However, careful investigation is necessary to ensure no malicious activity is occurring behind these alerts.
  ### Blind Spots and Assumptions
  Assumptions regarding this rule include that all relevant events are being logged properly in Windows Security logs, and filters are set to capture instances of risky flag usage. Potential blind spots may arise from legitimate administrative activities that trigger the same events, leading to false positives. Additionally, if not all systems are configured to log the necessary events, malicious configurations may escape detection, allowing adversaries to exploit potential vulnerabilities in certificate template configurations.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
