title: Invoke-Obfuscation Via Use MSHTA - Security
id: 9b8d9203-4e0f-4cd9-bb06-4cc4ea6d0e9a
related:
- id: 7e9c7999-0f9b-4d4a-a6ed-af6d553d4af4
  type: derived
status: test
description: Detects Obfuscated Powershell via use MSHTA in Scripts
references:
- https://github.com/SigmaHQ/sigma/issues/1009     # (Task31)
author: Nikita Nazarov, oscd.community
date: 2020-10-09
modified: 2022-11-29
tags:
- attack.defense-evasion
- attack.t1027
- attack.execution
- attack.t1059.001
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
  selection:
    EventID: 4697
    ServiceFileName|contains|all:
    - 'mshta'
    - 'vbscript:createobject'
    - '.run'
    - 'window.close'
  condition: selection
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  This detection rule identifies potentially malicious activity involving obfuscated PowerShell execution via Microsoft HTML Application Host (MSHTA). The rule specifically tracks Windows Security Event ID 4697, which logs the installation of a new service. It looks for the presence of specific keywords associated with the MSHTA executable, such as "vbscript:createobject," ".run," and "window.close." These keywords indicate that the service creation is likely being used to execute obfuscated scripts, which are common techniques employed by attackers to bypass security measures and execute malicious commands. The related MITRE ATT&CK techniques highlighted by this rule include T1027 (Obfuscated Files or Information) and T1059.001 (PowerShell), making it relevant for detecting defense evasion tactics executed through PowerShell scripts.
  ### Investigation Steps
  - **Check Relevant Logs:** Review Windows Security Event Logs for Event ID 4697 to validate the occurrence and details of the service creation related to MSHTA.
  - **Analyze Execution Context:** Use EDR tools to analyze the process tree and command line arguments associated with the detected event, focusing on any suspicious or unexpected parameters that may indicate malicious intent.
  - **Search for Malicious Activity:** Investigate the system and application logs for any additional suspicious activities or events that occurred prior to or following the detected event ID, to gather contextual information about potential persistence mechanisms.
  - **Identify Network Connections:** Inspect network traffic logs (NDR) to identify any outbound connections initiated by the detected MSHTA process, which could help in understanding the intended communication with external infrastructure.
  ### Prioritization
  This alert is rated as high severity as obfuscated PowerShell scripts are a common tactic for executing further malicious payloads within an environment, potentially leading to unauthorized data access or destruction.
  ### Blind Spots and Assumptions
  This rule may not trigger if the logging for Event ID 4697 is not properly configured or enabled within the environment. It may also fail to pick up threats if attackers use different methods to execute similar obfuscation techniques, such as directly invoking PowerShell without MSHTA or utilizing different, less common obfuscation methods. Additionally, if legitimate applications utilize similar patterns (e.g., legitimate use of VBScript in MSHTA), this could result in false positives.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and clarity, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
