title: ADCS Certificate Template Configuration Vulnerability
id: 5ee3a654-372f-11ec-8d3d-0242ac130003
status: test
description: Detects certificate creation with template allowing risk permission subject
references:
- https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
author: Orlinum , BlueDefenZer
date: 2021-11-17
modified: 2022-12-25
tags:
- attack.privilege-escalation
- attack.credential-access
logsource:
  product: windows
  service: security
  definition: Certificate services loaded a template would trigger event ID 4898 and
    certificate Services template was updated would trigger event ID 4899. A risk
    permission seems to be coming if template contain specific flag.
detection:
  selection1:
    EventID: 4898
    TemplateContent|contains: 'CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT'
  selection2:
    EventID: 4899
    NewTemplateContent|contains: 'CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT'
  condition: selection1 or selection2
falsepositives:
- Administrator activity
- Proxy SSL certificate with subject modification
- Smart card enrollement
level: low
notes: |
  ### Technical Context
  This Sigma rule identifies potentially risky configurations in Active Directory Certificate Services (ADCS) that involve certificate templates. Specifically, it detects instances where the certificate creation process includes a template that allows users to specify risky permissions, indicated by the presence of the `CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT` flag. The rule looks for specific event IDs (4898 for certificate template creation and 4899 for updates to existing templates) generated by Windows security logs related to Certificate Services. By monitoring these logs, the rule helps ensure that only appropriately configured templates are used, thus mitigating the risk of privilege escalation and credential access.
  ### Investigation Steps
  - Utilize your EDR solution to query for recent process creation events and check for any unauthorized changes to ADCS certificate templates, particularly those involving the `CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT`.
  - Review Windows Security event logs specifically for Event IDs 4898 and 4899 to verify any recent occurrences of certificate template modifications. Cross-reference these events with user activity logs for unusual account behaviors.
  - Check proxy logs to see if external connections were established following the creation or update of the risky certificate templates, as these may indicate potential exploitation attempts.
  - Analyze cloud platform logs (if applicable) to identify any anomalous activities linked to user accounts that created or updated certificate templates, particularly focusing on permissions granted.
