title: Invoke-Obfuscation CLIP+ Launcher - Security
id: 4edf51e1-cb83-4e1a-bc39-800e396068e3
related:
- id: f7385ee2-0e0c-11eb-adc1-0242ac120002
  type: derived
status: test
description: Detects Obfuscated use of Clip.exe to execute PowerShell
references:
- https://github.com/SigmaHQ/sigma/issues/1009      # (Task 26)
author: Jonathan Cheong, oscd.community
date: 2020-10-13
modified: 2022-11-27
tags:
- attack.defense-evasion
- attack.t1027
- attack.execution
- attack.t1059.001

logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
  selection:
    EventID: 4697
    ServiceFileName|contains|all:
    - 'cmd'
    - '&&'
    - 'clipboard]::'
  condition: selection
falsepositives:
- Unknown
level: high
notes: |
  ### Technical Context
  The "Invoke-Obfuscation CLIP+ Launcher 
  - Security" detection rule is designed to identify potentially malicious use of the command-line clipboard through the `Clip.exe` utility in Windows, specifically when it is used in an obfuscated manner to execute PowerShell commands. The rule focuses on monitoring Event ID 4697 from Windows Security logs, which pertains to process creation events. By filtering for command-line inputs that include certain keywords, such as `cmd`, `&&`, and `clipboard]::`, the rule aims to detect suspicious combinations that are indicative of defense evasion techniques outlined in the MITRE ATT&CK framework, particularly the tactics of execution (T1059.001) and defense evasion (T1027).
  The underlying technical data sources include Windows Security logs to track the invocation of the `Clip.exe` command and PowerShell execution. Anomalies within these logs present an opportunity to detect actors attempting to conceal malicious activities by embedding commands within clipboard interactions, hence blending in with legitimate activities.
  ### Investigation Steps
  - **Check Windows Security Logs:** Review Event ID 4697 logs in Windows Security to identify the specific occurrences of `Clip.exe` usage and the associated command-line parameters.
  - **Correlate with EDR Data:** Use your EDR solution to investigate the endpoint involved. Look for suspicious process execution patterns and any obfuscation techniques employed in the command-line arguments.
  - **Examine User Context:** Analyze the user account that executed the command for any potential red flags, such as unfamiliar accounts or unusual access patterns in the past hour.
  - **Assess Network Activity:** Investigate network connections made by the host during the time frame of the alert. Check if any outbound connections were made to known malicious IPs or domains.
  ### Prioritization
  This alert is classified as high severity because obfuscation techniques that leverage benign utilities such as `Clip.exe` may indicate an advanced threat actor attempting to evade detection. Such tactics could lead to payload execution, data exfiltration, or lateral movement within the environment.
  ### Blind Spots and Assumptions
  This rule may not be triggered if the logging for Event ID 4697 is disabled or improperly configured within the organization's security policies. Additionally, if an adversary successfully disguises their activities further or modifies command structures to avoid the specified keywords, the detection may fail. It is assumed that defenders have visibility into relevant security logs and that there are no significant gaps in endpoint monitoring.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
