title: Microsoft Malware Protection Engine Crash
id: 545a5da6-f103-4919-a519-e9aec1026ee4
related:
- id: 6c82cf5c-090d-4d57-9188-533577631108
  type: similar
status: test
description: This rule detects a suspicious crash of the Microsoft Malware Protection
  Engine
references:
- https://bugs.chromium.org/p/project-zero/issues/detail?id=1252&desc=5
- https://technet.microsoft.com/en-us/library/security/4022344
author: Florian Roth (Nextron Systems)
date: 2017-05-09
modified: 2023-04-14
tags:
- attack.defense-evasion
- attack.t1211
- attack.t1562.001
logsource:
  product: windows
  service: application
    # warning: The 'data' field used in the detection section is the container for the event data as a whole. You may have to adapt the rule for your backend accordingly
detection:
  selection:
    Provider_Name: 'Application Error'
    EventID: 1000
    Data|contains|all:
    - 'MsMpEng.exe'
    - 'mpengine.dll'
  condition: selection
falsepositives:
- MsMpEng might crash if the "C:\" partition is full
level: high
notes: |
  ### Technical Context
  This Sigma rule is designed to detect abnormal crashes of the Microsoft Malware Protection Engine, which is an integral component of Windows Defender. The rule specifically looks for Application Error logs (Event ID 1000) that indicate crashes involving the "MsMpEng.exe" process and its associated dynamic link library "mpengine.dll." These events are collected from the Windows application logs, which serve as a crucial data source for identifying potential malware-related issues or stability problems that could be indicative of larger security threats. Monitoring these logs can help analysts discern between genuine errors and potential exploit attempts that leverage vulnerabilities within security products.
  ### Investigation Steps
  - Investigate the incident using the EDR tool to find additional context around the crash, including any related processes or threads that were active at the time of the event.
  - Review the Windows event logs to capture any preceding events that could have contributed to the crash, including any suspicious activities or configuration changes.
  - Use AV logs to confirm whether any recent malware detections were flagged around the time of the crash, particularly focusing on events involving the MsMpEng.exe process.
  - Check any relevant application behavior on remote or cloud-based instances of Windows Defender using security tools integrated with AWS, GCP, or Azure environments to determine if similar incidents have occurred in a broader context.
