title: Sysmon Configuration Change
id: 8ac03a65-6c84-4116-acad-dc1558ff7a77
status: test
description: Detects a Sysmon configuration change, which could be the result of a
  legitimate reconfiguration or someone trying manipulate the configuration
references:
- https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
author: frack113
date: 2022-01-12
tags:
- attack.defense-evasion
logsource:
  product: windows
  service: sysmon
detection:
  selection:
    EventID: 16
    # To avoid FP just add
    # filter:
    #      ConfigurationFileHash: 'SHA256=The_Hash_Of_Your_Valid_Config_XML'
    # condition: selection and not filter
  condition: selection
falsepositives:
- Legitimate administrative action
level: medium
notes: |
  ### Technical Context
  The "Sysmon Configuration Change" detection rule identifies event log entries that indicate changes to Sysmon's configuration. Specifically, it targets Event ID 16, which represents a modification in the Sysmon configuration file—changes that may be legitimate administrative adjustments or potentially malicious acts aiming to obscure monitoring activities. By detecting these changes, the rule enables analysts to discern whether configurations are being manipulated by authorized personnel or by threat actors attempting to evade detection mechanisms. Utilizing telemetry from the Windows Event Logs, specifically focusing on Sysmon, responders can effectively track and analyze configuration alterations. This rule aligns with the MITRE ATT&CK technique of Defense Evasion, as attackers frequently modify security tools to shield their activities from visibility.
  ### Investigation Steps
  - **Review Sysmon Event Logs**: Use your SIEM to filter for Event ID 16 within Sysmon logs. Investigate the specific changes made and the user account responsible for the modification.
  - **Correlate with User Activity**: Check for any concurrent activities from the user account involved, particularly processes initiated around the same time, using EDR solutions to understand if any suspicious behavior is present.
  - **Assess Configuration Integrity**: If available, compare the modified configuration with a known good configuration file hash to determine if the change was authorized or if it deviated from expected settings.
  - **Consult Change Management Records**: If your organization maintains change logs, verify against these records to confirm whether the configuration change was part of a scheduled or approved maintenance action.
  ### Prioritization
  This alert is classified as medium severity due to the potential implications of unauthorized changes to monitoring configurations, which could signify a preparatory step by an attacker aiming to evade detection and may require immediate investigation to mitigate risks.
  ### Blind Spots and Assumptions
  This rule may not fire in environments where Sysmon is not deployed or where logging for Event ID 16 is not enabled. Additionally, legitimate administrative changes can trigger false positives if not properly filtered; hence, having a valid configuration hash is critical. An assumption is made that all administrative activity is logged, but if logs are deleted or if Event ID 16 is suppressed, a true malicious configuration change may go undetected.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and relevance, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
