title: Sysmon Configuration Error
id: 815cd91b-7dbc-4247-841a-d7dd1392b0a8
status: test
description: Detects when an adversary is trying to hide it's action from Sysmon logging
  based on error messages
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1562.001/T1562.001.md
- https://talesfrominfosec.blogspot.com/2017/12/killing-sysmon-silently.html
author: frack113
date: 2021-06-04
modified: 2022-07-07
tags:
- attack.defense-evasion
- attack.t1564
logsource:
  product: windows
  category: sysmon_error
detection:
  selection_error:
    Description|contains:
    - 'Failed to open service configuration with error'
    - 'Failed to connect to the driver to update configuration'
  filter_generic_english:
    Description|contains|all:
    - 'Failed to open service configuration with error'
    - 'Last error: The media is write protected.'
  filter_by_errorcode:
    Description|contains:
    - 'Failed to open service configuration with error 19'
    - 'Failed to open service configuration with error 93'
  condition: selection_error and not 1 of filter*
falsepositives:
- Legitimate administrative action
level: high
notes: |
  ### Technical Context
  The "Sysmon Configuration Error" detection rule focuses on identifying instances where an adversary may attempt to manipulate or obscure Sysmon logging functionalities. By monitoring Windows Sysmon error logs, this rule captures specific error messages that indicate potential evasion techniques employed by attackers. Specifically, the rule looks for log entries that contain phrases such as "Failed to open service configuration with error" or "Failed to connect to the driver to update configuration," alongside certain error codes. These messages can signal attempts by an adversary to hinder Sysmon's capability to log processes and other critical activities on a system, making the detection vital for maintaining visibility into malicious actions. The technique referenced is consistent with **MITRE ATT&CK Tactics: Defense Evasion, Technique T1564**.
  ### Investigation Steps
  - **Review Sysmon Logs:** Check the Sysmon error logs for events that match the specified descriptions to understand the context and scope of the potential evasion attempt.
  - **Cross-Reference with EDR:** Utilize the EDR tool to correlate the time of the detected error with any unusual process creation or modification activities in the same timeframe to identify potential adversary obfuscation efforts.
  - **Analyze System Services:** Investigate the services that Sysmon relies on to ensure they are running correctly and have not been tampered with or disabled by privileged users or adversaries.
  - **Check for Legitimate Actions:** Determine if the alerts correlate with legitimate administrative actions by documenting changes made by trusted personnel during the time frame of the error messages.
  ### Prioritization
  With a high-severity level assigned to this alert, it indicates a significant risk that an adversarial actor is attempting to evade detection mechanisms within the environment. Rapid investigation is required to ensure the integrity of logging persists and to assess any potential compromises.
  ### Blind Spots and Assumptions
  The rule assumes that all Sysmon logs are being collected without interruptions, and it may not fire if logging configurations are intentionally misconfigured or if logs are purged. Additionally, an adversary might employ more sophisticated methods to evade detection, such as using custom logging frameworks that do not trigger Sysmon errors, thus eluding this detection entirely. Responders should be aware of the potential for false negatives in environments where administrative tasks may frequently generate similar error messages.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality and comprehensiveness, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
