title: Sysmon Configuration Modification
id: 1f2b5353-573f-4880-8e33-7d04dcf97744
status: test
description: Detects when an attacker tries to hide from Sysmon by disabling or stopping
  it
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1562.001/T1562.001.md
- https://talesfrominfosec.blogspot.com/2017/12/killing-sysmon-silently.html
author: frack113
date: 2021-06-04
modified: 2022-08-02
tags:
- attack.defense-evasion
- attack.t1564
logsource:
  product: windows
  category: sysmon_status
detection:
  selection_stop:
    State: Stopped
  selection_conf:
  - 'Sysmon config state changed'
  filter:
    State: Started
  condition: 1 of selection_* and not filter
falsepositives:
- Legitimate administrative action
level: high
notes: |
  ### Technical Context
  The "Sysmon Configuration Modification" detection rule is designed to monitor and alert on potential tampering with the Sysmon service, specifically when an attacker attempts to disable or stop it. Sysmon, which provides detailed logs of system activity, is crucial for monitoring malicious behavior, and disabling it is a common tactic employed by threat actors to evade detection. This rule looks for relevant changes in the Sysmon service state, specifically when it is transitioned from a running state ("Started") to a stopped state ("Stopped"). Additionally, it checks for modifications to the Sysmon configuration state, which could indicate an attacker’s attempt to hinder the logging of important events. This rule aligns with the MITRE ATT&CK tactic of Defense Evasion (T1564), specifically focusing on those techniques that seek to change the operational parameters of defense mechanisms.
  The key technical data sources leveraged by this rule include Windows Sysmon logs, which document the state of the Sysmon process and any changes made to its configuration. By correlating these events and pinpointing discrepancies where Sysmon is stopped while unexpected configuration changes occur, analysts can identify possible malicious behavior that seeks to conceal ongoing attacks.
  ### Investigation Steps
  - **Verify Sysmon Service Status:** Check the Sysmon service on the compromised system using EDR to confirm whether it is indeed running or has been stopped as indicated by the alert.
  - **Review Sysmon Logs:** Utilize Sysmon logs to pinpoint when the service was last stopped and any configuration changes made immediately before or after, looking for signs of unauthorized activity.
  - **Analyze Related Process Activity:** Investigate any processes that were active at the time of the event that may have attempted to interact with or modify Sysmon, using tools like Windows Event Logs and EDR.
  - **Check Other Security Logs:** Review other relevant Windows Security and System logs to identify additional suspicious activity or auditor events that may correlate with Sysmon's status change.
  ### Prioritization
  This alert is marked as high severity given that any attempt to disable or modify Sysmon poses a significant risk to the organization's security posture, potentially indicating an active intrusion or preparation for further malicious activities.
  ### Blind Spots and Assumptions
  This rule may fail to trigger in scenarios where legitimate administrative actions invoke changes to the Sysmon service or configuration. Adversaries may also employ sophisticated evasion techniques or custom scripts that do not involve standard Sysmon state changes, thus bypassing detection. Additionally, if Sysmon has been uninstalled without generating the appropriate logs, the detection will not activate. It's important for detection engineers to consider that false positives may occur from legitimate IT operations and to establish robust alert validation procedures.
  > **Disclaimer:** This investigation guide was created using generative AI technology and has not been reviewed for its accuracy and relevance. While every effort has been made to ensure its quality, we recommend validating the content and adapting it to suit specific environment and operational needs. Please communicate any changes to the detection engineering team.
